{...}:
{
# enables history in the iex shell
env.ERL_AFLAGS="-kernel shell_history enabled";
env.DISCORD_TOKEN="";
env.BNET_CLIENT_ID="";
env.BNET_CLIENT_SECRET="";
env.TWITCH_CLIENT_ID="";
env.TWITCH_CLIENT_SECRET="";
env.TWITCH_BOT_OAUTH="";
# env.SIGNUP_TOKEN="";
# env.ESPORTS_EARNINGS_API_KEY="";
# env.REQT100_ACCESS_TOKEN="";
# env.REQT100_ACCESS_TOKEN_SECRET="";
# env.REQT100_CONSUMER_KEY="";
# env.REQT100_CONSUMER_SECRET="";
# env.PATREON_CLIENT_ID="";
# env.PATREON_CLIENT_SECRET="";
# env.PATREON_REDIRECT_URI="";
# env.PATREON_ACCESS_TOKEN="";
# env.PATREON_REFRESH_TOKEN="";
}
