version: '3'
services:
  postgres:
    image: postgres:12
    container_name: DtopDB
    ports: 
      - "2470:5432"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=DtopDB 
    restart: unless-stopped

