defmodule Backend.PlayerInfo do
  @moduledoc false
  alias Backend.Blizzard
  alias Backend.Battlenet
  alias Backend.MastersTour
  alias Backend.MastersTour.InvitedPlayer
  alias Backend.Infrastructure.PlayerNationalityCache, as: PlayerNationality
  alias Backend.EsportsEarnings
  alias Backend.PrioritizedBattletagCache
  @type country_code :: <<_::2>>
  @type player_info :: %{region: Blizzard.region() | nil, country: country_code | nil}

  @na_players MapSet.new([
                "brimful",
                "NoHandsGamer",
                "killinallday",
                "Impact",
                "Tincho",
                "PapaJason",
                "Villain",
                "Dabs",
                "Gle",
                "Zeh",
                "Innovation",
                "TheLastChamp",
                "IrvinG",
                "Pavelingbook",
                "HSKeDaiBiao",
                "caravaggio8",
                "Cesky",
                "Rpbalance",
                "V1ctor",
                "Turner",
                "LeandroLeal"
              ])
  @eu_players MapSet.new([
                "GrJim",
                "xBlyzes",
                "AyRoK",
                "totosh",
                "DeadDraw",
                "Furyhunter",
                "Kalàxz",
                "xxCJ42069xx",
                "Zhym",
                "Leta",
                "Turbon1ck",
                "Fenomeno",
                "Dreivo",
                "Gaby",
                "Dizdemon",
                "petrovic",
                "Cosmo",
                "Paradox",
                "iNS4NE",
                "Warma",
                "hunterace",
                "Guntofire",
                "Hoej",
                "NikolajHoej",
                "Yogg",
                "s8ris",
                "Habugabu",
                "DikiyZver",
                "Matty"
              ])
  @ap_players MapSet.new([
                "yeschicken",
                "Alan870806",
                "Bankyugi",
                "TIZS",
                "撒旦降臨",
                "로좀",
                "Duelist",
                "Staz",
                "shanOz",
                "Hi3",
                "GivePLZ",
                "hone",
                "RaFaEl",
                "LojomHS",
                "Bloodtrail",
                "ShroomJuice",
                "WaningMoon"
              ])

  @cn_players MapSet.new([
                "AjjXiGuan",
                "TNCAnswer",
                "Liooon",
                "VKLiooon",
                "SNBrox",
                "SNJing",
                "iGSyf",
                "RNGKylinS",
                "Bourbon",
                "LPXHope",
                "RNGLeaoh",
                "WEYuansu"
              ])
  def relegated_gms({2020, 2}) do
    MapSet.new([
      "Kolento",
      "Pavel",
      "hunterace",
      "Purple",
      "PNC",
      "PapaJason",
      "SamuelTsao",
      "Staz",
      "FroStee"
    ])
  end

  def relegated_gms({2021, 1}) do
    MapSet.new([
      "Ryvius",
      "kin0531",
      "SilverName",
      "BoarControl",
      "Justsaiyan",
      "justsaiyan",
      "Warma",
      "Flurry",
      "Firebat",
      "Empanizado"
    ])
    |> MapSet.union(relegated_gms({2020, 2}))
  end

  def relegated_gms(_), do: MapSet.new()

  # from liquidpedia and some hardcoded
  @player_nationalities %{
    "HyunMini" => "South Korea",
    "1123630728" => "Singapore",
    "A83650" => "Poland",
    "AKAWonder" => "Spain",
    "ANCOLL" => "Indonesia",
    "ARee" => "United States",
    "AVC" => "Italy",
    "Aaron" => "Singapore",
    "Abelmo" => "South Korea",
    "Ace" => "China",
    "AceOfAces" => "Singapore",
    "Activelee" => "United States",
    "AdiK" => "Philippines",
    "AdnQn" => "Belgium",
    "Adriano" => "France",
    "Ahrrr" => "Ukraine",
    "Akatsu" => "Colombia",
    "Akumaker" => "Australia",
    # "Alan870806" => "United States", # not according to blizzard
    "Alb987" => "Italy",
    "Albo21" => "Chile",
    "Alchemixt" => "United States",
    "Alesh" => "Czech Republic",
    "Alexieishere" => "Indonesia",
    "AlivZ" => "France",
    "Alkylone" => "France",
    "Allad" => "Ukraine",
    "Alliestrasza" => "United States",
    "Alteex" => "Russia",
    "Alutemu" => "Japan",
    "Aly33sida" => "Vietnam",
    "Amaz" => "Hong Kong",
    "Amnesiac" => "United States",
    "Amyks" => "Poland",
    "Anderonie" => "China",
    "Angel" => "Vietnam",
    "AngryCarp" => "South Korea",
    "Anguistar" => "Chile",
    "Anothersy" => "Thailand",
    "Ant" => "China",
    "Ant" => "United States",
    "Anthony04" => "Ukraine",
    "Apxvoid" => "Canada",
    "Aquablad" => "United Kingdom",
    "Arneej" => "Belgium",
    "ArtZa-R.Devil" => "Thailand",
    "ArtZaRDevil" => "Thailand",
    "Arthur" => "China",
    "Artosis" => "United States",
    "Arya" => "Spain",
    "Asmodai" => "Norway",
    "Astrogation" => "United States",
    "Auryn" => "Turkey",
    "Avelline" => "Greece",
    "Aven" => "Singapore",
    "Aviera" => "Canada",
    "Ayata" => "Turkey",
    "Azmo" => "Japan",
    "Azumo" => "United States",
    "Azur" => "Australia",
    "Azuresky" => "Singapore",
    "BIGEldrazi" => "Spain",
    "BLIGHT" => "Singapore",
    "BTuan" => "Vietnam",
    "BabyBear" => "Belgium",
    "Backspace" => "United States",
    "Bacon" => "Canada",
    "BaiZe" => "China",
    "BananaAche" => "Thailand",
    "Bankai" => "Spain",
    "Bankyugi" => "Thailand",
    "Bastossavoie" => "France",
    "Bbgungun" => "Malaysia",
    "BeNice" => "Germany",
    "Beefsteak" => "Philippines",
    "Beherit" => "Greece",
    "Bekooze" => "Romania",
    "Benene" => "Netherlands",
    "Bequiet" => "Germany",
    "Bertels" => "Italy",
    "BestUdyrEu" => "Bulgaria",
    "Bestmarmotte" => "France",
    "BibleThump" => "Vietnam",
    "BigBen" => "United Kingdom",
    "BlackCrossXIII" => "Vietnam",
    "Blackout" => "United Kingdom",
    "Blah" => "United States",
    "Blank" => "Germany",
    "BlazingGlory" => "Bulgaria",
    "BloodTrail" => "Taiwan",
    "Blue" => "China",
    "BoarControl" => "United Kingdom",
    "Bompi" => "Sweden",
    "Borosan" => "France",
    "Bors" => "Germany",
    "Bozo" => "Switzerland",
    "Bozzzton" => "Sweden",
    "Brad" => "United States",
    "Brammerham" => "United Kingdom",
    "Breath" => "China",
    "BreizhPunisher" => "France",
    "BrownstonE" => "Thailand",
    "BunnyHoppor" => "Germany",
    "Burr0" => "Germany",
    "C4mlann" => "Germany",
    "Cabrix" => "Spain",
    "Caimiao" => "China",
    "CaptainRage" => "Latvia",
    "CaraCute" => "Philippines",
    "Caravaggio" => "United States",
    "Carlosvela" => "Vietnam",
    "Carvalho" => "Brazil",
    "Casie" => "Germany",
    "CelticGuard" => "Brazil",
    "Ceto" => "Germany",
    "Ch0pP33r" => "Germany",
    "Chachaboizz" => "Denmark",
    "Chacruna" => "Denmark",
    "Chakki" => "United States",
    "Chalk" => "Philippines",
    "Chandyland" => "United States",
    "Chani" => "Vietnam",
    "ChapmanUK" => "United Kingdom",
    "Charge" => "Vietnam",
    "Charon" => "France",
    "Chatthon" => "France",
    "Che0nsu" => "South Korea",
    "ChiakiNanami" => "Russia",
    "ChinaYLD" => "China",
    "Chinoize" => "Belgium",
    "ChongGEr" => "Malaysia",
    "ChronoX" => "Brazil",
    "Chungfr" => "Singapore",
    "Cipher" => "United Kingdom",
    "CitizenNappa" => "Australia",
    "Cloudre01" => "Malaysia",
    "Coglorin" => "Brazil",
    "Coldhands" => "United Kingdom",
    "Comm" => "China",
    "Condauco" => "Vietnam",
    "Conrad" => "United States",
    "Control" => "Canada",
    "Cookmysock" => "United Kingdom",
    "Coreia" => "Brazil",
    "Cosmo" => "Russia",
    "CraWleR" => "Lithuania",
    "Crane333" => "Denmark",
    "CrazyMageeee" => "Vietnam",
    "Crazymageeee" => "Vietnam",
    "Creapz" => "Finland",
    "Crumoet" => "Austria",
    "Crumpled" => "Singapore",
    "CsJoKerD1123" => "Singapore",
    "Csnoobie" => "Singapore",
    "CtrlCCtrlV" => "Thailand",
    "CupCake" => "Denmark",
    "Cyal" => "Canada",
    "Cydonia" => "Canada",
    "CzechCloud" => "Czech Republic",
    "D3n0r" => "Netherlands",
    "DDaHyoNi" => "South Korea",
    "DTwo" => "United States",
    "Dalesom" => "Spain",
    "DanPoh" => "Philippines",
    "Dandido" => "Sweden",
    "DaneHearth" => "United Kingdom",
    "Daniel" => "Canada",
    "Danielctin14" => "Romania",
    "Danswf" => "United Kingdom",
    "Darkwonyx" => "Sweden",
    "Darroch" => "United Kingdom",
    "Dart" => "United States",
    "Dartill" => "France",
    "DawN" => "South Korea",
    "Day&#91;9&#93;" => "United States",
    "DeadDraw" => "United Kingdom",
    "DeadFaith" => "Croatia",
    "Deathboose" => "Sweden",
    "DeathstarV3" => "United States",
    "Deela" => "Germany",
    "DeerNadia" => "United States",
    "Demigod" => "United States",
    "Den" => "France",
    "DenimBlue7" => "Germany",
    "Denker" => "Chile",
    "Dennisgosu" => "Malaysia",
    "DerZerfetzer" => "Germany",
    "DerZerfetzer" => "Germany",
    "DerZerfetzer/Crane333" => "Denmark",
    "DerZerfetzer/SolidReste" => "Latvia",
    "Dethelor" => "Greece",
    "Dethklok" => "Belarus",
    "DevilMat" => "Italy",
    "Dexter" => "Canada",
    "DiegoDias" => "Brazil",
    "Diggen" => "Norway",
    "Digital" => "Philippines",
    "Digitald" => "Malaysia",
    "Disdai" => "Thailand",
    "Disguised Toast" => "Canada",
    "Dizdemon" => "France",
    "DocPwn" => "Canada",
    "Doffyduff" => "France",
    "Dog" => "United States",
    "Dogggg" => "China",
    "Donten" => "China",
    "Dorathor" => "Denmark",
    "DouAhou" => "Indonesia",
    "DrBoom" => "Portugal",
    "DrHippi" => "Ukraine",
    "DrJikininki" => "United States",
    "DrLister" => "Germany",
    "Dragodz" => "Indonesia",
    "DragonBall" => "Vietnam",
    "Draz" => "France",
    "Dreivo" => "France",
    "Duncan" => "United Kingdom",
    "Durlic" => "France",
    "Dustiny" => "Vietnam",
    "Dzianydruid" => "Poland",
    "EHWAHHH" => "Singapore",
    "EK" => "China",
    "EMEMME11" => "Thailand",
    "ETC" => "United States",
    "Eddie" => "Canada",
    "EducatedCollins" => "United States",
    "Edygarcia" => "Vietnam",
    "EggY" => "Canada",
    "Ek0p" => "Germany",
    "ElMachico" => "Italy",
    "Elfandor" => "Germany",
    "Eliah" => "Czech Republic",
    "ElkY" => "France",
    "ElleWhyJay" => "Singapore",
    "Eloise" => "China",
    "Empanizado" => "Mexico",
    "Ender" => "Australia",
    "Epricesx" => "Vietnam",
    "Epsylon" => "Mexico",
    "ErA" => "Sweden",
    "Ersee" => "Finland",
    "Esosek" => "Czech Republic",
    "Estefania" => "Spain",
    "Evangelion" => "Spain",
    "Exigo" => "Hungary",
    "Exilessmath" => "France",
    "ExonaToR" => "Malaysia",
    "Exonator" => "Malaysia",
    "ExplodingCow" => "United Kingdom",
    "FRID" => "United States",
    "FaKe" => "Germany",
    "Faceopei" => "Germany",
    "Faeli" => "Czech Republic",
    "Fafa" => "South Africa",
    "Falcone" => "United Kingdom",
    "Faramir" => "Germany",
    "Fearsyndrome" => "Poland",
    "Felkeine" => "France",
    "FenTyrris" => "Austria",
    "Fenom" => "United States",
    "Fenomeno" => "Greece",
    "Ferdz" => "Philippines",
    "Fertygo" => "Indonesia",
    "FibEli3" => "Greece",
    "Fibonacci" => "Canada",
    "Findan" => "Czech Republic",
    "Firebat" => "United States",
    "Firsttime" => "Vietnam",
    "Fizdarth" => "Malaysia",
    "FlawlesSlays" => "United Kingdom",
    "Fled" => "Brazil",
    "FlerFlegma" => "Poland",
    "Flix" => "Germany",
    "Floflo" => "France",
    "Fluffy" => "Sweden",
    "Flurry" => "South Korea",
    "FlècheNoire" => "France",
    "Forsen" => "Sweden",
    "Foufouman" => "France",
    "Fox" => "Russia",
    "Fr0zen" => "United States",
    "Franky" => "Germany",
    "Freakeh" => "Sweden",
    "FreddyB" => "Denmark",
    "Freshca" => "United States",
    "Frezzar" => "Sweden",
    "Friiz" => "France",
    "FroStee" => "Australia",
    "Frodan" => "United States",
    "FrozenIce" => "Taiwan",
    "Fujitora" => "Turkey",
    "Fungggg" => "Hong Kong",
    "Funkymonk" => "Netherlands",
    "Fuoliver" => "China",
    "Furyhunter" => "Denmark",
    "Futureshock" => "Japan",
    "Gaara" => "Bosnia and Herzegovina",
    "Gaboumme" => "France",
    "Gallon" => "United States",
    "GameKing" => "Austria",
    "Garangana0" => "Philippines",
    "Garifar" => "Brazil",
    "GarkGus" => "Mexico",
    "Gaskin" => "United Kingdom",
    "GeeMoney" => "Sweden",
    "GeneraL" => "Russia",
    "Genghis" => "Spain",
    "Genji27" => "Philippines",
    "GeorgeDanzer" => "Germany",
    "Georgec" => "United Kingdom",
    "Gera89" => "Italy",
    "Ghost" => "South Korea",
    "GibsoNR" => "Singapore",
    "Gilgamesh" => "Malaysia",
    "Gladen99" => "Argentina",
    "Gladial" => "France",
    "Glaser" => "Israel",
    "Gnimsh" => "Poland",
    "God Slayer" => "China",
    "Gomms" => "Thailand",
    "Gram" => "Slovakia",
    "Grayj" => "Ukraine",
    "GreenMemory" => "China",
    "GreenWood" => "Germany",
    "Greensheep" => "United Kingdom",
    "Grimmjow" => "Slovenia",
    "GroSSo" => "France",
    "GuN" => "Spain",
    "Guiyze" => "United States",
    "GundamFlame" => "Japan",
    "Guntofire" => "France",
    "Gunzerker" => "France",
    "Gusonaj" => "Switzerland",
    "Guukboii" => "Belgium",
    "HAVATITE" => "Philippines",
    "HOYLA" => "Croatia",
    "Hadek" => "Switzerland",
    "Hades" => "Brazil",
    "Hafu" => "United States",
    "Haizstuff" => "Singapore",
    "Hamster" => "China",
    "HariSeldon" => "Spain",
    "Harleen" => "Russia",
    "Haslr" => "United Kingdom",
    "Haslr" => "United Kingdom",
    "Hatul" => "Israel",
    "Hawkeye" => "Greece",
    "Heib" => "Finland",
    "HelloLeeroy" => "United Kingdom",
    "Henry" => "Thailand",
    "Herudra" => "Denmark",
    "Hoej" => "Denmark",
    "Horo" => "Japan",
    "Hosty" => "Canada",
    "HotMEOWTH" => "United States",
    "Hotform" => "Canada",
    "Hovati16" => "Vietnam",
    "HuLu" => "China",
    "Humanscorpio" => "Iran",
    "HunterMing" => "China",
    "Hunterace" => "Norway",
    "Hymnrael" => "Philippines",
    "Hyped" => "United States",
    "Hypno" => "Switzerland",
    "ID of player here" => "Spain",
    "ILDaMih" => "Argentina",
    "IceFox" => "China",
    "Icegirl" => "United States",
    "Icem4n" => "Spain",
    "Icsm" => "Russia",
    "IgnisSolus" => "Indonesia",
    "Ignite" => "Portugal",
    "Ihsanity" => "Indonesia",
    "Ikarus" => "Germany",
    "Ike" => "United States",
    "Ikealyou" => "Poland",
    "Ikki" => "Vietnam",
    "Illusi0nxz" => "Singapore",
    "ImagineAName" => "Germany",
    "Impact" => "Canada",
    "Impyyyyy" => "Denmark",
    "Inderen" => "Denmark",
    "Iner" => "Russia",
    "Infernity" => "Vietnam",
    "Infi" => "China",
    "Iniven" => "Italy",
    "Innovation" => "United States",
    "Insane" => "Croatia",
    "Insania" => "Netherlands",
    "Insom" => "United States",
    "Islandcat" => "China",
    "Izual512" => "Poland",
    "Izzy" => "Peru",
    "J4CKIECHAN" => "United Kingdom",
    "J4YOU" => "Ukraine",
    "J4kubb" => "Poland",
    "JAB" => "United States",
    "JBillyB" => "United States",
    "JINGJINGBRAH" => "Philippines",
    "Jac0b0" => "Spain",
    "JackPot" => "Thailand",
    "JackyChan" => "Hong Kong",
    "Jakattack" => "New Zealand",
    "JamesHugs" => "United Kingdom",
    "Janetzky" => "Finland",
    "JangeN" => "Sweden",
    "Janos" => "Denmark",
    "Jarla" => "Czech Republic",
    "JasonZhou" => "China",
    "Jeanno" => "Hong Kong",
    "Jengo" => "Bulgaria",
    "JensonCCS" => "Malaysia",
    "JetLaw" => "United States",
    "Jia" => "Philippines",
    "Jimbot" => "United Kingdom",
    "Jing" => "China",
    "Jinsoo" => "South Korea",
    "Jizzes" => "Singapore",
    "Joaquin" => "Argentina",
    "JohnnyStone" => "Austria",
    "Johnnybambou" => "France",
    "Jolbakk" => "Estonia",
    "Jonpi" => "United Kingdom",
    "Jooltz" => "Netherlands",
    "Joth703" => "Indonesia",
    "Journey" => "Singapore",
    "Juristis" => "Ukraine",
    "Justsaiyan" => "United States",
    "Jvetonor" => "France",
    "K1NG" => "Spain",
    "Kaisercillo" => "Spain",
    "Kaizeen 3" => "Philippines",
    "KaizerSosa" => "Switzerland",
    "Kaka" => "Malaysia",
    "Kalas" => "France",
    "Kaldi" => "Iceland",
    "Kalàxz" => "France",
    "Kamahl" => "Poland",
    "Kananai" => "Malaysia",
    "Kaor" => "Italy",
    "Kapi" => "Thailand",
    "Karlis" => "Latvia",
    "Karmoth" => "Germany",
    "Kartoha" => "Belarus",
    "Kat" => "United Kingdom",
    "Katsucurry" => "Singapore",
    "Keith" => "Singapore",
    "Kelvinfeels" => "Thailand",
    "KepSId" => "Indonesia",
    "Keruya" => "Philippines",
    "KevinKookies" => "United States",
    "KevveC" => "Sweden",
    "Khaius" => "Singapore",
    "Khamul" => "Austria",
    "Khwarizmi" => "Austria",
    "KiRu" => "South Korea",
    "Kibler" => "United States",
    "Kimmy" => "China",
    "Kisstafer" => "Canada",
    "Kitkatz" => "Canada",
    "Kleenex" => "Belgium",
    "Kly" => "Vietnam",
    "Kno" => "Japan",
    "Knugen" => "Sweden",
    "Kolbein" => "Norway",
    "Kolento" => "Ukraine",
    "Konokun1" => "Vietnam",
    "Koroneko" => "Japan",
    "Korvus" => "Russia",
    "Kostron" => "Spain",
    "KowFox" => "China",
    "Koyuki" => "United States",
    "Kranich" => "South Korea",
    "Kripparrian" => "Canada",
    "Kroba" => "Greece",
    "Krycekid" => "Indonesia",
    "Ktfyellow" => "Thailand",
    "Kufdon" => "Finland",
    "Kungen" => "Sweden",
    "Kunzi" => "Germany",
    "Kuonet" => "United States",
    "Kurious" => "Thailand",
    "Kycoo" => "Germany",
    "Kykounet" => "France",
    "L0rinda" => "United Kingdom",
    "LBYS" => "United States",
    "lambyseries" => "Singapore",
    "LazyA" => "Portugal",
    "Leadpaint" => "United States",
    "Leaoh" => "China",
    "Ledah" => "Thailand",
    "Legendaren" => "Sweden",
    "LegolaS" => "Brazil",
    "Lemongreen" => "Austria",
    "Leo324a" => "Singapore",
    "Leomane" => "Brazil",
    "Leta" => "Italy",
    "Level9001" => "Canada",
    "LiBo" => "China",
    "Lifecoach" => "Germany",
    "Lightsworn" => "Thailand",
    "Lii" => "United States",
    "Likeabawse" => "Greece",
    "Limilyz" => "Thailand",
    "Linessa" => "France",
    "LionKing" => "China",
    "Liooon" => "China",
    "Logan" => "Greece",
    "LonelyGod" => "China",
    "LooGiiQQ" => "France",
    "LookSam" => "South Korea",
    "Lothar" => "Poland",
    "LoveCX" => "China",
    "Lowelo" => "France",
    "Loxodontes" => "Brazil",
    "Loxodontes" => "Brazil",
    "Loyan" => "Poland",
    "Lube" => "Thailand",
    "LucasCrt" => "Brazil",
    "Lucete" => "South Korea",
    "Lucken" => "Poland",
    "Lucky" => "Spain",
    "LuckyClover" => "Poland",
    "Luffy" => "Canada",
    "Luhanluan1" => "Vietnam",
    "Luker" => "Canada",
    "Lukesten" => "Germany",
    "Lupord" => "Spain",
    "LvGe" => "China",
    "M1SA" => "Greece",
    "MATSURI" => "Japan",
    "MM78" => "Russia",
    "MYRIN" => "Malaysia",
    "MaSsan" => "USA",
    "Mael" => "France",
    "Mage" => "New Zealand",
    "MagicWind" => "China",
    "Magicgeek" => "France",
    "Magoho" => "France",
    "Malteemil" => "Denmark",
    "MalygosTW" => "Taiwan",
    "Malza" => "South Korea",
    "Mariodela" => "Spain",
    "MartinCreek" => "Sweden",
    "Marzito" => "Greece",
    "MatTheGreat" => "Denmark",
    "Matixo" => "Poland",
    "Matt" => "Italy",
    "Maur1" => "Finland",
    "Maverick" => "Belgium",
    "Max" => "United Kingdom",
    "MaxCapone" => "Germany",
    "Mayhem" => "United Kingdom",
    "MaynardTcoX" => "Germany",
    "Meati" => "United Kingdom",
    "Meliador" => "Italy",
    "Melody" => "China",
    "MentorWings" => "Vietnam",
    "MessyOD" => "Netherlands",
    "Metalcat" => "Uruguay",
    "Michr" => "Germany",
    "Microwaves" => "Singapore",
    "MightnMagic" => "Singapore",
    "Mikka" => "Thailand",
    "MikkelGoh" => "Singapore",
    "Mikolop" => "Poland",
    "Mimring" => "France",
    "Mirrari" => "Czech Republic",
    "MisterMongo" => "Germany",
    "Mito" => "Netherlands",
    "Mitsuhide" => "Netherlands",
    "Mlasic" => "Slovenia",
    "Mmikiez" => "Thailand",
    "Modernleper" => "United Kingdom",
    "Mogu.Ywai" => "Malaysia",
    "Mokochiro" => "Indonesia",
    "MoleGel" => "Brazil",
    "Monk" => "United States",
    "Monsanto" => "Canada",
    "MooDy" => "Romania",
    "Moosey" => "USA",
    "Morrison" => "France",
    "Moyen" => "Germany",
    "MrClowny" => "France",
    "MrHumor" => "China",
    "MrLego" => "Australia",
    "MrYagut" => "Germany",
    "Muzzy" => "United States",
    "Mysterious" => "United Kingdom",
    "MïmeMaster" => "France",
    "NaRa" => "South Korea",
    "NabUttE" => "Sweden",
    "Nagura" => "Italy",
    "Naiman" => "Kazakhstan",
    "Nalguidan" => "Argentina",
    "NaviOOT" => "Australia",
    "Neilyo" => "Vietnam",
    "Neirea" => "Ukraine",
    "Nerthus" => "Croatia",
    "Ness" => "Brazil",
    "Ness" => "United Kingdom",
    "Neves" => "Brazil",
    "Neviilz" => "Malta",
    "NewMeta" => "Belarus",
    "Nexos" => "Czech Republic",
    "NexxGen" => "Vietnam",
    "Nibbler" => "Czech Republic",
    "Nicholena" => "United States",
    "NickChipper" => "Ukraine",
    "Nicslay" => "Germany",
    "NightWalk" => "China",
    "Niizuma" => "France",
    "NikolajHoej" => "Denmark",
    "NjiNjiNji" => "Germany",
    "NoName" => "Belarus",
    "NoRage" => "Finland",
    "NoTomorrow" => "China",
    "Noflame" => "Russia",
    "Nostam" => "United States",
    "NotoriousH2" => "Korea",
    "Noxious" => "Canada",
    "Ntnt2" => "Vietnam",
    "Nuko" => "France",
    "Numberguy" => "Denmark",
    "Nxek" => "Malaysia",
    "Nyhx" => "Germany",
    "NyikNyukNyk" => "Indonesia",
    "OMjuwax" => "France",
    "Odemian" => "France",
    "Ojoke" => "Thailand",
    "Oki9155" => "Poland",
    "OldBoy" => "Ukraine",
    "Olesami" => "Ukraine",
    "Oliech" => "Belgium",
    "Oloninho" => "Poland",
    "OmegaZero" => "China",
    "Orange" => "Sweden",
    "OrigiN" => "France",
    "Osha" => "United Kingdom",
    "Osiris" => "Germany",
    "Osonodel" => "Russia",
    "Ostkaka" => "Sweden",
    "Osyris" => "France",
    "Otsuna" => "France",
    "Ouate" => "Canada",
    "P4wnyhof" => "Germany",
    "PHONETAP" => "United States",
    "PNC" => "Argentina",
    "Palmblad" => "South Korea",
    "PapaJason" => "United States",
    "Paradox" => "United Kingdom",
    "Pathra" => "New Zealand",
    "Patoyao" => "Thailand",
    "Patrycjusz" => "Poland",
    "Patryn" => "Netherlands",
    "Pavel" => "Russia",
    "PawlaczGMD" => "Poland",
    "Pegasos" => "Korea",
    "Pegy" => "China",
    "Pelletire" => "Canada",
    "PenhaDani" => "Hungary",
    "Perna" => "Brazil",
    "Pewpewurface" => "Singapore",
    "Pilou" => "France",
    "Pinche" => "Argentina",
    "Pini" => "Spain",
    "Pinpingho" => "Taiwan",
    "Pipoanhat" => "Vietnam",
    "PipoyCute" => "Philippines",
    "Pizza" => "United States",
    "Pog1ak" => "Philippines",
    "Pokrovac" => "Czech Republic",
    "Polarhase" => "Germany",
    "Polsomrang" => "Thailand",
    "Pompi" => "Philippines",
    "Pool8" => "Italy",
    "Portex" => "Netherlands",
    "Powder" => "Sweden",
    "PoweR" => "Czech Republic",
    "Preach" => "Germany",
    "Preglow" => "Germany",
    "Prelude" => "Canada",
    "Prince" => "China",
    "ProfessorOak" => "Australia",
    "Psyhodel" => "Russia",
    "PurpleDrank" => "Canada",
    "QiuTu" => "China",
    "Quatro" => "Poland",
    "Quubeeee" => "Philippines",
    "Qwerty97" => "United States",
    "RDee" => "Sweden",
    "RENMEN" => "Russia",
    "RarestSolanum" => "Ireland",
    "Rase" => "Brazil",
    "RastaFish" => "Czech Republic",
    "Ratsmah" => "United States",
    "Raven" => "United Kingdom",
    "Ravexnous" => "Philippines",
    "Ray" => "Switzerland",
    "RayAllen" => "China",
    "RcobGaming" => "Spain",
    "Rdu" => "Romania",
    "ReVengeCCS" => "Malaysia",
    "ReWinD" => "Germany",
    "RealTerror" => "Canada",
    "Realz" => "United States",
    "Reckful" => "United States",
    "Reliquary" => "Portugal",
    "RenieHouR" => "South Korea",
    "RenoJackson" => "Vietnam",
    "Rewind" => "Spain",
    "Reynad" => "United States",
    "Rezdan" => "Indonesia",
    "Richard Knight" => "China",
    "Rikitikitavi" => "Russia",
    "Riku97" => "Spain",
    "RoL" => "Turkey",
    "Robin" => "China",
    "RobinWho" => "Germany",
    "Roger" => "Taiwan",
    "Romeus" => "Italy",
    "Rooftrellen" => "United States",
    "RossFTW" => "Switzerland",
    "Rostovmax" => "Russia",
    "Rosty" => "United States",
    "Ruby" => "Japan",
    "Rugal" => "China",
    "RunAndGun" => "China",
    "Runaways13" => "Poland",
    "Ryder" => "United States",
    "Ryvius" => "South Korea",
    "Ryzen" => "United States",
    "S4mule" => "Spain",
    "S8ris" => "Lithuania",
    "SCACC" => "Italy",
    "SGAhIce" => "Singapore",
    "SUPERPOGI" => "Philippines",
    "Saliom" => "Algeria",
    "SamuelTsao" => "Taiwan",
    "SargentoSC" => "Brazil",
    "SatriaIsenk" => "Indonesia",
    "SaucisseSwan" => "Belgium",
    "Savjz" => "Finland",
    "Savvat" => "Russia",
    "Scarakye" => "United Kingdom",
    "Schismatron" => "Sweden",
    "ScreaM" => "Thailand",
    "Scruffy" => "Czech Republic",
    "Scully" => "Ireland",
    "Season" => "China",
    "SebastianJo" => "Austria",
    "Seeker" => "Germany",
    "Seiko" => "Germany",
    "Seloko" => "Spain",
    "Seltzer" => "United States",
    "Semijew" => "Sweden",
    "Sen" => "Taiwan",
    "Senfglas" => "Germany",
    "Sequinox" => "Singapore",
    "Setzer" => "Russia",
    "Seulsiho" => "South Korea",
    "SeungJae" => "South Korea",
    "Sevel" => "Poland",
    "SevenRuo" => "China",
    "Seyberoz" => "Thailand",
    "SgtFaucon" => "Canada",
    "ShangHigh" => "South Korea",
    "Shark" => "Vietnam",
    "Shaxy" => "Taiwan",
    "Shindo" => "Singapore",
    "Shinypants" => "Singapore",
    "Shiraz" => "Denmark",
    "Shoop" => "United States",
    "ShtanUdachi" => "Russia",
    "Shu1k" => "United States",
    "Shurripe" => "China",
    "Shy" => "Hong Kong",
    "SieraN" => "Poland",
    "SilentStorm" => "Bulgaria",
    "SilentStorm" => "Canada",
    "SilentStormy" => "Singapore",
    "Silfer" => "Singapore",
    "Silhan" => "Slovakia",
    "SilverByz" => "Singapore",
    "SilverName" => "Russia",
    "Silverreald" => "Thailand",
    "Silvors" => "Ukraine",
    "SineX" => "Germany",
    "Sintolol" => "Germany",
    "Sipiwi94" => "Denmark",
    "SirSalty" => "United Kingdom",
    "SjoW" => "Sweden",
    "Sjoesie" => "Belgium",
    "Skip" => "Germany",
    "Skylink" => "Portugal",
    "SlAyEr" => "Vietnam",
    "SleepyDragon" => "Singapore",
    "SleepyShaman" => "China",
    "Slugg" => "Denmark",
    "Slysssa" => "United States",
    "Slytha" => "Spain",
    "Snail" => "Argentina",
    "SneerySpace" => "Philippines",
    "Snoodyboo" => "Spain",
    "SnowKiss" => "China",
    "Snowdrop" => "Kazakhstan",
    "Snowman" => "Italy",
    "Sohigh666" => "Singapore",
    "Sonecarox" => "Brazil",
    "SongBird" => "United States",
    "Sooni" => "South Korea",
    "Sottle" => "United Kingdom",
    "Soundfx" => "Singapore",
    "Spl33N" => "France",
    "Spo" => "Sweden",
    "Squit" => "Turkey",
    "StanCifka" => "Czech Republic",
    "Stark" => "Argentina",
    "Staz" => "Philippines",
    "Steelo" => "South Korea",
    "StefanSim" => "Romania",
    "Stijn" => "Belgium",
    "Stilinski" => "Russia",
    "StrifeCro" => "United States",
    "StrikeReaper" => "Switzerland",
    "Styxon" => "Czech Republic",
    "SudaKa" => "Uruguay",
    "SuperJJ" => "Germany",
    "Surk" => "Sweden",
    "Surrender" => "South Korea",
    "Sveiks" => "Estonia",
    "Swaggermeist" => "Italy",
    "SwaggyG" => "USA",
    "Swidz" => "France",
    "Switch" => "Philippines",
    "Sword" => "China",
    "SylvanHunter" => "Philippines",
    "Syn" => "United Kingdom",
    "T1mme" => "Germany",
    "T4COTASTIC" => "Brazil",
    "TSMFedEx" => "Vietnam",
    "Tacticalzz" => "Germany",
    "Taesang" => "South Korea",
    "TaeyeonK" => "Vietnam",
    "Talion" => "Canada",
    "TanakhT" => "Czech Republic",
    "TangZ" => "Thailand",
    "Tansoku" => "Japan",
    "Tarei" => "United States",
    "Tarkam" => "Denmark",
    "Tars" => "France",
    "Tasu17" => "Thailand",
    "TcG" => "Vietnam",
    "TeamAmerica" => "United States",
    "TechnoGoose" => "Sweden",
    "Teebs" => "Canada",
    "Tempo" => "Chile",
    "TerrenceM" => "United States",
    "Th3RaT" => "United States",
    "Thalai" => "Spain",
    "ThatGuy" => "Sweden",
    "ThatsAdmirable" => "United States",
    "TheBigMac" => "Philippines",
    "TheEnclase" => "Germany",
    "TheFallen" => "Spain",
    "TheJordude" => "Canada",
    "TheOddOne" => "Canada",
    "TheOneJack" => "Singapore",
    "TheOneJack" => "Vietnam",
    "ThePandorica" => "Singapore",
    "TheRabbin" => "Switzerland",
    "TheTeacher" => "Portugal",
    "TheViper94" => "Portugal",
    "Thefishou" => "France",
    "Theo" => "Netherlands",
    "Theude" => "Germany",
    "Thijs" => "Netherlands",
    "ThroneHS" => "Hong Kong",
    "ThunderUP" => "Turkey",
    "Thuongthoi" => "Vietnam",
    "TicTac" => "Belgium",
    "TiddlerCelestial" => "China",
    "TidesofTime" => "United States",
    "Tiggerr" => "Singapore",
    "Timon" => "Vietnam",
    "Timpotz" => "Indonesia",
    "Tincho" => "Argentina",
    "TingTong" => "New Zealand",
    "Tinghu" => "Singapore",
    "TinyGrimes" => "United States",
    "TitanFall" => "Vietnam",
    "Tito" => "United States",
    "Tixuty" => "France",
    "Toastmonster" => "United Kingdom",
    "Tomas" => "Lithuania",
    "Tomflr" => "Australia",
    "Tomwilliams" => "United Kingdom",
    "Topdeck" => "America",
    "Topheroes" => "Thailand",
    "Topopablo11" => "Chile",
    "Torlk" => "France",
    "TrainingDay" => "Serbia",
    "Trec" => "France",
    "Tredsred" => "Japan",
    "TristanJ" => "Sweden",
    "TrollTrollTroll" => "Malaysia",
    "Trump" => "United States",
    "Trunks" => "China",
    "Truong" => "Vietnam",
    "Tsukivet" => "Vietnam",
    "Tsukiviet" => "Vietnam",
    "Tuan" => "Vietnam",
    "Turna" => "Italy",
    "TurtlePower" => "Singapore",
    "Tuttek" => "Poland",
    "Tvist" => "Belarus",
    "Twink" => "Denmark",
    "Twisted" => "Canada",
    "Twixsen" => "Sweden",
    "Twizz" => "Australia",
    "TwoBiers" => "Germany",
    "TxiN" => "Brazil",
    "Tyderian" => "Czech",
    "Tyler" => "Vietnam",
    "Uberer" => "Finland",
    "UchihaSaske" => "Peru",
    "Un33d" => "France",
    "Unwi" => "Russia",
    "Unwi2" => "Russia",
    "Valeera" => "China",
    "Valenash" => "Italy",
    "Valky" => "Vietnam",
    "VampAurora" => "Greece",
    "Vanik" => "Czech Republic",
    "VanillaT" => "Indonesia",
    "VanillaTitan" => "Czech Republic",
    "Vardu" => "Finland",
    "Varranis" => "United States",
    "Via" => "Czech Republic",
    "Villain" => "United States",
    "Vinny" => "Brazil",
    "Vinz" => "France",
    "Viper" => "Germany",
    "ViperPro" => "Thailand",
    "Virtual" => "Taiwan",
    "Vlps" => "United States",
    "Vortex" => "Netherlands",
    "Wampie" => "Finland",
    "WaningMoon" => "Philippines",
    "Warma" => "France",
    "Wayne" => "China",
    "Weghuz" => "Sweden",
    "Well played, I'm sorry" => "China",
    "Wharp" => "Spain",
    "Whiplash" => "United Kingdom",
    "Wifecoach" => "Austria",
    "Windello" => "France",
    "Winterchill" => "Philippines",
    "WoT" => "Colombia",
    "Wolcat" => "Italy",
    "Wolfsbanee" => "Singapore",
    "Woven" => "Turkey",
    "Wuaschtsemme" => "Germany",
    "Wufflerman" => "Singapore",
    "XHope" => "China",
    "Xeno" => "Poland",
    "Xernfaex" => "Poland",
    "XiaoDai" => "Taiwan",
    "XiaoGz" => "China",
    "XiaoT" => "China",
    "XiaoYao" => "China",
    "XingSu" => "China",
    "Xixo" => "Germany",
    "Xyzor" => "Thailand",
    "Xzirez" => "Norway",
    "Yawgmoth" => "Italy",
    "Yhone" => "Austria",
    "Yinus" => "Mexico",
    "Yogg" => "France",
    "YouLove" => "China",
    "Yoyokix" => "Switzerland",
    "YuYi" => "China",
    "Yugiohggg" => "Malaysia",
    "Yulsic" => "Hong Kong",
    "Yuri" => "Malaysia",
    "Yuriii" => "Singapore",
    "Zadkiel" => "Germany",
    "Zadkiel" => "Philippines",
    "Zalae" => "United States",
    "Zananananan" => "Germany",
    "ZawiszaMiko" => "Poland",
    "Zeal123" => "Italy",
    "Zenbadsu" => "Philippines",
    "Zentinel" => "Thailand",
    "Zetalot" => "Poland",
    "ZhangBo" => "China",
    "Zhym" => "France",
    "Ziegenteig" => "Austria",
    "Zihao" => "China",
    "Zorkthar" => "Norway",
    "Zoro" => "China",
    "Zozus" => "Poland",
    "Zuhex" => "Spain",
    "Zuka" => "Portugal",
    "Zyrios" => "Germany",
    "aKiSera" => "Malaysia",
    "alexnoehr" => "Denmark",
    "amaze" => "Singapore",
    "angeloshaggy" => "Romania",
    "aqua" => "Japan",
    "b4bana" => "Germany",
    "b787" => "Japan",
    "barret" => "Spain",
    "berserkci" => "Turkey",
    "bj0rN" => "Singapore",
    "blitzchung" => "Hong Kong",
    "bloodyface" => "United States",
    "buer" => "China",
    "cgsongbird" => "United States",
    "chaoznoob" => "Singapore",
    "chosenone" => "Peru",
    "chosenone" => "United States",
    "cookie" => "Denmark",
    "darksub" => "Argentina",
    "dawido" => "Poland",
    "deads17" => "Finland",
    "demonhunter" => "Vietnam",
    "dogmeat" => "Poland",
    "dontbemad" => "Germany",
    "eXoBLaZeR" => "Philippines",
    "edanco" => "Peru",
    "eg99" => "Russia",
    "endmyturn" => "Thailand",
    "endzaz" => "Thailand",
    "espumito" => "Spain",
    "esteban" => "France",
    "farm4fame" => "Russia",
    "fateos" => "Austria",
    "feicxant" => "Ukraine",
    "fr0d0b0ls0n" => "Spain",
    "freddykuhl" => "Germany",
    "friki" => "Bulgaria",
    "fzmushko" => "Belarus",
    "gcttirth" => "India",
    "glory" => "Japan",
    "handsomeguy" => "South Korea",
    "heisnotaxel" => "Singapore",
    "hinaya" => "Japan",
    "honbee" => "South Korea",
    "iBeennn" => "Mexico",
    "iBeennn" => "Mexico",
    "iNS4NE" => "Ukraine",
    "iamThanh" => "Germany",
    "illness" => "Italy",
    "illsory" => "Australia",
    "itsProtoHype" => "United States",
    "jakaso27" => "United States",
    "jambre" => "United Kingdom",
    "jjangnara" => "South Korea",
    "joster" => "America",
    "kalhspera" => "Greece",
    "kbushi" => "Netherlands",
    "killinallday" => "USA",
    "kin0531" => "Hong Kong",
    "kolmari" => "Germany",
    "kroz0" => "United Kingdom",
    "lalasong" => "Malaysia",
    "languagehacker" => "Canada",
    "las3ed" => "Tunisia",
    "lbdutchboy" => "Netherlands",
    "levik" => "Russia",
    "ligagamejoth" => "Indonesia",
    "longshi" => "China",
    "lorn" => "Singapore",
    "losefield" => "Hong Kong",
    "lovelychook" => "China",
    "lvxiaobu" => "China",
    "magicamy" => "South Korea",
    "makgi" => "Thailand",
    "martim" => "Slovakia",
    "matff" => "Poland",
    "mbpro" => "Germany",
    "meanio" => "Vietnam",
    "mess" => "Canada",
    "mikeboy" => "Germany",
    "nexok40" => "Indonesia",
    "noblord" => "United States",
    "ntR" => "Norway",
    "oyatsu" => "Japan",
    "ozzywcg" => "Philippines",
    "pAc" => "France",
    "posesi" => "Japan",
    "rayC" => "USA",
    "reall" => "Taiwan",
    "sapphire" => "Italy",
    "scarface" => "France",
    "seogui" => "South Korea",
    "shianna" => "Germany",
    "sianhalf" => "Singapore",
    "strikeright" => "South Korea",
    "taeng2" => "South Korea",
    "tholwmenos" => "Greece",
    "tom60229" => "Taiwan",
    "tomof" => "France",
    "trahison" => "Japan",
    "tranzit" => "South Korea",
    "vcT" => "Brazil",
    "weasel" => "France",
    "wkyew90" => "Malaysia",
    "wojekxd" => "Poland",
    "wtybill" => "United States",
    "wwlos" => "United States",
    "xBlaine" => "Germany",
    "xBlyzes" => "France",
    "xNVx" => "Singapore",
    "xxx" => "Singapore",
    "xyuan" => "China",
    "yilingsama" => "China",
    "yoitsflo" => "United States",
    "younTheory" => "Switzerland",
    "zGGLeoz" => "Vietnam",
    "zlsjs" => "United States",
    "zumpp" => "Finland",
    "reqvam" => "Croatia",
    "D0nkey" => "Croatia",
    "WEStone" => "China",
    "azuuu" => "South Korea",
    "Jajo" => "South Korea",
    "WEYuyi" => "China",
    "iGXc" => "China",
    "Cptnkitty" => "Netherlands",
    "GamerRvg" => "USA",
    "PeaceHawk" => "Peru",
    "BlizzconJan" => "Czech Republic",
    "LFYueying" => "China",
    "RNGLys" => "China",
    "gle" => "USA",
    "VKDiana" => "China",
    "Lambyseries" => "Singapore",
    "Komik" => "Germany",
    "taroimo" => "Japan",
    "Aojiru" => "Japan",
    "decisivebeat" => "Russia",
    "Lwd12318" => "Hong Kong",
    "cagnetta99" => "Italy",
    "DreadEye" => "United States",
    "coolkid2001" => "Australia",
    "Thund3r" => "Italy",
    "D0nkey" => "Croatia",
    "maneti" => "Spain"
  }

  @nationality_to_region %{
    "Argentina" => :US,
    "Belize" => :US,
    "Bolivia" => :US,
    "Brazil" => :US,
    "Canada" => :US,
    "Chile" => :US,
    "Colombia" => :US,
    "Costa Rica" => :US,
    "Ecuador" => :US,
    "El Salvador" => :US,
    "Guatemala" => :US,
    "Honduras" => :US,
    "Jamaica" => :US,
    "Mexico" => :US,
    "Nicaragua" => :US,
    "Paraguay" => :US,
    "Peru" => :US,
    "Puerto Rico" => :US,
    "United States of America" => :US,
    "United States" => :US,
    "USA" => :US,
    "Uruguay" => :US,
    "Venezuela" => :US,
    "Australia" => :AP,
    "Indonesia" => :AP,
    "Hong Kong" => :AP,
    "India" => :AP,
    "Japan" => :AP,
    "Macau" => :AP,
    "Malaysia" => :AP,
    "New Zealand" => :AP,
    "The Philippines" => :AP,
    "Singapore" => :AP,
    "South Korea" => :AP,
    "Taiwan" => :AP,
    "Thailand" => :AP,
    "Vietnam" => :AP,
    "Algeria" => :EU,
    "Austria" => :EU,
    "Bahrain" => :EU,
    "Belarus" => :EU,
    "Belgium" => :EU,
    "Bulgaria" => :EU,
    "Croatia" => :EU,
    "Czech Republic" => :EU,
    "Denmark" => :EU,
    "Egypt" => :EU,
    "Estonia" => :EU,
    "Finland" => :EU,
    "France" => :EU,
    "Germany" => :EU,
    "Greece" => :EU,
    "Hungary" => :EU,
    "Iceland" => :EU,
    "Iraq" => :EU,
    "Ireland" => :EU,
    "Israel" => :EU,
    "Italy" => :EU,
    "Jordan" => :EU,
    "Kazakhstan" => :EU,
    "Kuwait" => :EU,
    "Latvia" => :EU,
    "Lebanon" => :EU,
    "Libya" => :EU,
    "Lithuania" => :EU,
    "Luxembourg" => :EU,
    "Malta" => :EU,
    "Morocco" => :EU,
    "Netherlands" => :EU,
    "Norway" => :EU,
    "Oman" => :EU,
    "Poland" => :EU,
    "Portugal" => :EU,
    "Romania" => :EU,
    "Russia" => :EU,
    "Serbia" => :EU,
    "Slovakia" => :EU,
    "Slovenia" => :EU,
    "Kingdom of Saudi Arabia" => :EU,
    "South Africa" => :EU,
    "Spain" => :EU,
    "State of Qatar" => :EU,
    "Sweden" => :EU,
    "Switzerland" => :EU,
    "Tunisia" => :EU,
    "Turkey" => :EU,
    "Ukraine" => :EU,
    "United Arab Emirates" => :EU,
    "United Kingdom" => :EU,
    "China" => :CN
  }

  @alpha2_to_region %{
    "KZ" => :EU,
    "PE" => :US,
    "MY" => :AP,
    "SA" => :EU,
    "TH" => :AP,
    "KW" => :EU,
    "AR" => :US,
    "AT" => :EU,
    "IT" => :EU,
    "GR" => :EU,
    "TR" => :EU,
    "JP" => :AP,
    "LT" => :EU,
    "JM" => :US,
    "BO" => :US,
    "FR" => :EU,
    "BZ" => :US,
    "QA" => :EU,
    "MO" => :AP,
    "RS" => :EU,
    "PL" => :EU,
    "HN" => :US,
    "TW" => :AP,
    "BR" => :US,
    "NL" => :EU,
    "IQ" => :EU,
    "PY" => :US,
    "CH" => :EU,
    "PH" => :AP,
    "SK" => :EU,
    "VN" => :AP,
    "CN" => :CN,
    "DZ" => :EU,
    "PT" => :EU,
    "ES" => :EU,
    "LV" => :EU,
    "UA" => :EU,
    "BH" => :EU,
    "EG" => :EU,
    "MX" => :US,
    "SV" => :US,
    "IN" => :AP,
    "LU" => :EU,
    "DE" => :EU,
    "NI" => :US,
    "CZ" => :EU,
    "HR" => :EU,
    "ZA" => :EU,
    "FI" => :EU,
    "PR" => :US,
    "IL" => :EU,
    "GB" => :EU,
    "JO" => :EU,
    "BE" => :EU,
    "DK" => :EU,
    "LB" => :EU,
    "OM" => :EU,
    "UY" => :US,
    "HU" => :EU,
    "EC" => :US,
    "NO" => :EU,
    "MA" => :EU,
    "HK" => :AP,
    "VE" => :US,
    "LY" => :EU,
    "CA" => :US,
    "SI" => :EU,
    "SE" => :EU,
    "MT" => :EU,
    "BG" => :EU,
    "IE" => :EU,
    "ID" => :AP,
    "AE" => :EU,
    "RO" => :EU,
    "NZ" => :AP,
    "RU" => :EU,
    "KR" => :AP,
    "EE" => :EU,
    "CO" => :US,
    "CR" => :US,
    "AU" => :AP,
    "GT" => :US,
    "SG" => :AP,
    "CL" => :US,
    "US" => :US,
    "TN" => :EU,
    "BY" => :EU,
    "IS" => :EU
  }
  def get_eligible_countries() do
    @alpha2_to_region |> Map.keys()
  end

  def country_to_region(cc), do: @alpha2_to_region[cc]

  def get_grandmasters_fot_promotion(season = {2020, 2}),
    do: get_grandmasters(:Jönköping, relegated_gms(season))

  def get_grandmasters_for_promotion(season = {2021, 1}),
    do: get_grandmasters(:Montréal, relegated_gms(season)) ++ ["Briarthorn"]

  def get_grandmasters_for_promotion({2021, 2}),
    do:
      get_grandmasters({2021, 1}) ++
        [
          "Leta",
          "Warma",
          "Frenetic",
          "justsaiyan",
          "DreadEye",
          "Impact",
          "Fled",
          "GivePLZ",
          "Hi3",
          "lambyseries"
        ]

  def get_grandmasters_for_promotion(_), do: []

  def get_grandmasters({2021, 1}) do
    get_grandmasters(:Ironforge, ["justsaiyan", "撒旦降臨", "bloodyface", "Che0nsu"] |> MapSet.new()) ++
      ["lunaloveee", "Tincho", "che0nsu"]
  end

  def get_grandmasters(rts = reference_tour_stop, relegated) do
    Backend.MastersTour.list_invited_players(rts)
    |> Enum.filter(fn %{reason: r, official: o} -> String.contains?(r, "Grandmaster") end)
    |> Enum.map(fn %{battletag_full: bf} ->
      Backend.MastersTour.InvitedPlayer.shorten_battletag(bf)
    end)
    |> Enum.filter(fn n -> !MapSet.member?(relegated, n) end)
    |> Enum.uniq()
  end

  def get_esportsgold_nationality(player) do
    ((pi = Backend.EsportsGold.get_cached_info(player)) &&
       pi &&
       pi.nationality &&
       @nationality_to_region[pi.nationality]) || nil
  end

  def get_esports_earnings_region(player) do
    player
    |> EsportsEarnings.get_player_country()
    |> case do
      nil -> nil
      a2 -> @alpha2_to_region[a2]
    end
  end

  # for people that appear differently in my source
  def hack_name(name) do
    case name do
      "muzzy" -> "Muzzy"
      "justsaiyan" -> "Justsaiyan"
      "Bunnyhoppor" -> "BunnyHoppor"
      "Briarthorn" -> "brimful"
      _ -> name
    end
  end

  def same_player_override(player, new) do
    cond do
      player |> String.starts_with?("Jay#") -> player |> new.()
      true -> nil
    end
  end

  @spec get_region(String.t()) :: Blizzard.region()
  def get_region(full_or_short) do
    full_or_short
    |> get_country()
    |> case do
      nil -> nil
      cc -> @alpha2_to_region[cc]
    end

    # with nil <- full_or_short |> same_player_override(&new_get_region/1),
    # nil <- full_or_short |> region_from_override(),
    # nil <- full_or_short |> InvitedPlayer.shorten_battletag() |> old_get_region(),
    # nil <- full_or_short |> new_get_region() do
    # nil
    # else
    # r -> r
    # end
  end

  # def region_from_override(full_or_short) do
  # short = full_or_short |> InvitedPlayer.shorten_battletag()

  # nationality_overrides()
  # |> Map.get(short)
  # |> case do
  # nil -> nil
  # cc -> @alpha2_to_region[cc]
  # end
  # end

  def new_get_region(full_or_short),
    do: full_or_short |> PlayerNationality.get_country() |> country_to_region()

  def old_get_region(original_name) do
    player = original_name |> hack_name()

    cond do
      MapSet.member?(@na_players, player) ->
        :US

      MapSet.member?(@eu_players, player) ->
        :EU

      MapSet.member?(@ap_players, player) ->
        :AP

      MapSet.member?(@cn_players, player) ->
        :CN

      r = get_esports_earnings_region(player) ->
        r

      region = @nationality_to_region[@player_nationalities[player]] ->
        region

      true ->
        nil
    end
  end

  def nationality_overrides() do
    china =
      for n <- [
            "WedgmXmg",
            "LPTrunks",
            "SubUss",
            "GMLT",
            "LFyueying",
            "ADU",
            "RNGTyrion",
            "TainanWater",
            "旅店老闆",
            "PDA",
            "yoyo",
            "樂天盜賊",

            # maybe actually not china and Taiwan and no override
            "Allen",
            "maxchen",
            "Joy",
            "choco06743",
            "MagicPants",
            "jerry",
            "Asura",
            "SevenC"
          ],
          into: %{},
          do: {n, "CN"}

    %{
      "Thund3r" => "IT",
      "HSKeDaiBiao" => "US",
      "D0nkey" => "HR",
      "WEChengxin" => "CN",
      "Mysterious" => "PL",
      "Rpbalance" => "CN",
      "fire" => "KR",
      "Dennis" => "TW",
      "WEYoulove" => "CN",
      "WEBaKu" => "CN",
      "VKxhx" => "CN",
      "VKTianming" => "CN",
      "SNSyu" => "CN",
      "SNRugal" => "CN",
      "LPOmegaZero" => "CN",
      "LFZhoulang" => "CN",
      # correct but writing it here to know it's correct
      "destiny" => "CN",
      "BunnyHoppor" => "DE",
      "Tyler" => "VN",
      "edwin" => "CN",
      "illsory" => "AU",

      # BALKAN GENERATED MAY NOT BE ACCURATE
      "rudd33s" => "HR",
      "Tomac" => "HR",
      "djapeT" => "RS",
      "hotgirl" => "RS",
      "Mata" => "HR",
      "caiv" => "BA",
      "SansRivals" => "ME",
      "Joza" => "HR",
      "radx11" => "RS",
      "reqvam" => "HR",
      "Lip" => "HR",
      "LemyBiB" => "RS",
      "AleksandarNS" => "RS",
      "Sundayman" => "RS",
      "Djuka93" => "RS",
      "Phobus" => "HR",
      "Comarilion" => "RS",
      "Paljuha" => "HR",
      "Brazuka" => "RS",
      "Cifoni" => "RS",
      "divljasvinja" => "HR",
      "DusanSRB" => "RS",
      "XoroN" => "RS",
      "MiracLE" => "RS",
      "mlax" => "RS",
      "HurricaneBzz" => "HR",
      "Uberkaiser" => "RS",
      "TTVF134srb" => "RS",
      "D0nkey" => "HR",
      "Groinkpff" => "HR",
      "HeXXiX" => "MK",
      "CicoHS" => "HR",
      "Kajita" => "HR",
      "Blankieh" => "RS",
      "dimi" => "RS",
      "Antonini94" => "HR",
      "Pera" => "RS",
      "salebk4" => "RS",
      "dealwithit" => "HR",
      "NoReason" => "RS"
    }
    |> Map.merge(china)
  end

  @spec get_country(Blizzard.battletag()) :: country_code
  def get_country(battletag_full) do
    PrioritizedBattletagCache.get_long_or_short(battletag_full)
    |> case do
      %{country: c} -> c
      _ -> nil
    end

    # short =
    # battletag_full |> InvitedPlayer.shorten_battletag() |> MastersTour.fix_name() |> hack_name()

    # with nil <- battletag_full |> same_player_override(&new_get_country/1),
    # nil <- nationality_overrides() |> Map.get(short),
    # nil <- short |> old_get_country(),
    # nil <- battletag_full |> new_get_country() do
    # nil
    # else
    # c -> c
    # end
  end

  def new_get_country(full_or_short), do: full_or_short |> PlayerNationality.get_country()

  def old_get_country(short) do
    with old when old != :CN <- short |> old_get_region(),
         nil <- short |> EsportsEarnings.get_player_country() do
      nil
    else
      :CN -> "CN"
      c -> c
    end
  end

  def leaderboard_names(battletag_full), do: [InvitedPlayer.shorten_battletag(battletag_full)]
end
