defmodule Backend.Hearthstone.WhizbangHeroesArchetyper do
  @moduledoc "Archetyping for the whizbang heroes twist mode"
  import Backend.Hearthstone.DeckArchetyper, only: [min_count?: 3]
  alias Backend.Hearthtstone.DeckArchetyper

  @spec archetype(DeckArchetyper.card_info()) :: atom() | nil
  def archetype(card_info) do
    # generated in Scratchpad
    cond do
      min_count?(card_info, 14, [
        "Grave Defiler",
        "Taste of Chaos",
        "Chaos Strike",
        "Dryscale Deputy",
        "Fel Barrage",
        "Fossil Fanatic",
        "Multi-Strike",
        "Quick Pick",
        "Coordinated Strike",
        "Disciple of Argus",
        "Herald of Chaos",
        "Sigil of Time",
        "Stargazer Luna",
        "Archmage Vargoth",
        "Demonic Assault",
        "Fan the Hammer",
        "Metamorphosis",
        "Jotun, the Eternal",
        "Queen Azshara",
        "Chaos Creation",
        "Impfestation",
        "Expendable Performers",
        "Jace Darkweaver"
      ]) ->
        :"Illidan Stormrage"

      min_count?(card_info, 20, [
        "Elemental Evocation",
        "Devolving Missiles",
        "Elemental Allies",
        "Fire Fly",
        "Flame Geyser",
        "Kindling Elemental",
        "Synthesize",
        "Wailing Vapor",
        "Aqua Archivist",
        "Elementary Reaction",
        "Menacing Nimbus",
        "Sandstorm Elemental",
        "Sleetbreaker",
        "Spotlight",
        "Trusty Companion",
        "Arid Stormer",
        "Frostfin Chomper",
        "Gyreworm",
        "Lightning Storm",
        "Minecart Cruiser",
        "Baking Soda Volcano",
        "Dang-Blasted Elemental",
        "Al'ar",
        "Lilypad Lurker",
        "Mes'Adune the Fractured",
        "Tainted Remnant",
        "Waxadred",
        "Horn of the Windlord",
        "Baron Geddon",
        "Kalimos, Primal Lord",
        "Siamat",
        "Skarr, the Catastrophe",
        "Therazane",
        "Al'Akir the Windlord",
        "Ragnaros the Firelord"
      ]) ->
        :"Al'Akir the Windlord"

      min_count?(card_info, 20, [
        "Ivus, the Forest Lord",
        "Sir Finley, Sea Guide",
        "Sphere of Sapience",
        "Astalor Bloodsworn",
        "Bloodmage Thalnos",
        "Flint Firearm",
        "Archdruid Naralex",
        "Brann Bronzebeard",
        "Brightwing",
        "Flightmaster Dungar",
        "Mankrik",
        "SN1P-SN4P",
        "Blademaster Okani",
        "Korrak the Bloodrager",
        "Maiev Shadowsong",
        "Pozzik, Audio Engineer",
        "Emperor Thaurissan",
        "Loatheb",
        "Moonfang",
        "Overlord Runthak",
        "Zilliax",
        "Cairne Bloodhoof",
        "Gnomelia, S.A.F.E. Pilot",
        "Sylvanas Windrunner",
        "Dr. Boom",
        "Lor'themar Theron",
        "Mutanus the Devourer",
        "Siamat",
        "Goliath, Sneed's Masterpiece",
        "Jepetto Joybuzz",
        "Ozumat",
        "Alexstrasza the Life-Binder",
        "Yogg-Saron, Unleashed",
        "Neptulon the Tidehunter",
        "Raid Boss Onyxia"
      ]) ->
        :"Arch-Villain Rafaam"

      min_count?(card_info, 20, [
        "Blessing of Wisdom",
        "First Day of School",
        "Knight of Anointment",
        "Sanguine Soldier",
        "Argent Protector",
        "Blood Matriarch Liadrin",
        "Crooked Cook",
        "For Quel'Thalas!",
        "Hand of A'dal",
        "Hi Ho Silverwing",
        "Hydrologist",
        "Knife Juggler",
        "Manafeeder Panthara",
        "Sound the Bells!",
        "Squashling",
        "Acolyte of Pain",
        "Aldor Peacekeeper",
        "Alliance Bannerman",
        "Cathedral of Atonement",
        "Consecration",
        "Disco Maul",
        "Divine Favor",
        "Funkfin",
        "Goody Two-Shields",
        "Hammer of Wrath",
        "Keeper of Uldaman",
        "Magnifying Glaive",
        "Salhet's Pride",
        "Stargazer Luna",
        "Voracious Reader",
        "Warsong Commander",
        "Wickerflame Burnbristle",
        "Ancestral Guardian",
        "Crusader Aura",
        "Keeper's Strength"
      ]) ->
        :"Leeroy Jenkins"

      min_count?(card_info, 25, [
        "Arcane Wyrm",
        "Babbling Book",
        "Evocation",
        "Fire Fly",
        "First Day of School",
        "First Flame",
        "Jar Dealer",
        "Learn Draconic",
        "Magic Trick",
        "Synthesize",
        "Training Session",
        "Unstable Felbolt",
        "Violet Spellwing",
        "Wand Thief",
        "Astral Rift",
        "Dark Peddler",
        "Dryscale Deputy",
        "Expired Merchant",
        "Flint Firearm",
        "Mana Cyclone",
        "Primordial Glyph",
        "Prismatic Elemental",
        "Ram Commander",
        "Runed Orb",
        "Tiny Knight of Evil",
        "Unstable Portal",
        "Wandmaker",
        "Whelp Wrangler",
        "Arcsplitter",
        "Dark Skies",
        "Instructor Fireheart",
        "Messenger Raven",
        "Ravencaller",
        "Reckless Diretroll",
        "Trolley Problem",
        "Gloomstone Guardian",
        "Leyline Manipulator",
        "School Teacher",
        "Blast Wave",
        "Cobalt Spellkin",
        "Spawn of Deathwing",
        "Maruut Stonebinder",
        "Cho'gall",
        "Mana Giant",
        "Grand Magister Rommath"
      ]) ->
        :"Kael'Thas Sunstrider"

      min_count?(card_info, 18, [
        "Cactus Construct",
        "Living Roots",
        "Chaotic Consumption",
        "Forest Seedlings",
        "Grimoire of Sacrifice",
        "Lingering Zombie",
        "Plague of Flames",
        "Pop-Up Book",
        "Wicked Shipment",
        "Dreamway Guardians",
        "Haunted Creeper",
        "Mining Casualties",
        "Shrubadier",
        "Thorngrowth Sentries",
        "BEEEES!!!",
        "Darkshire Councilman",
        "Frostwolf Kennels",
        "Imp Gang Boss",
        "Plot of Sin",
        "Swipe",
        "Branching Paths",
        "Klaxxi Amber-Weaver",
        "Murlocula",
        "Flipper Friends",
        "Glowfly Swarm",
        "Swarm of Lightbugs",
        "Twilight Darkmender",
        "Ancient Shieldbearer",
        "Trial by Fire",
        "Twin Emperor Vek'lor"
      ]) ->
        :"C'Thun"

      min_count?(card_info, 28, [
        "Arcane Breath",
        "Cleric of Scales",
        "Flight of the Bronze",
        "Giftwrapped Whelp",
        "Sand Breath",
        "Twilight Whelp",
        "Alexstrasza's Champion",
        "Breath of Dreams",
        "Corrosive Breath",
        "Dragonmaw Sentinel",
        "Firetree Witchdoctor",
        "Lay Down the Law",
        "Nether Breath",
        "Netherspite Historian",
        "Redscale Dragontamer",
        "Splish-Splash Whelp",
        "Wyrmrest Agent",
        "Amber Whelp",
        "Breath of the Infinite",
        "Consecration",
        "Dragonrider Talritha",
        "Lightbringer's Hammer",
        "Lightning Breath",
        "Timewarden",
        "Desert Nestmatron",
        "Duskbreaker",
        "Future Emissary",
        "Molten Breath",
        "Blackwing Corruptor",
        "Chronobreaker",
        "Crazed Netherwing",
        "Dragonfire Potion",
        "Malygos, Aspect of Magic",
        "Onyxian Warder",
        "Aeon Reaver",
        "Candle Breath",
        "Nithogg",
        "Anachronos",
        "Murozond, Thief of Time",
        "Deathwing, Mad Aspect",
        "Murozond the Infinite",
        "Alexstrasza the Life-Binder",
        "Fye, the Setting Sun",
        "Ysera the Dreamer",
        "Raid Boss Onyxia"
      ]) ->
        :Nozdormu

      min_count?(card_info, 14, [
        "Arms Dealer",
        "Body Bagger",
        "Fistful of Corpses",
        "Heart Strike",
        "Lingering Zombie",
        "Plagued Grain",
        "Runes of Darkness",
        "Haunted Creeper",
        "Mining Casualties",
        "Acolyte of Death",
        "Corpse Farm",
        "Crop Rotation",
        "Eulogizer",
        "Unliving Champion",
        "Ymirjar Deathbringer",
        "Malignant Horror",
        "Sickly Grimewalker",
        "Tomb Guardians",
        "Corpse Bride",
        "Stitched Giant",
        "The Scourge"
      ]) ->
        :"The Lich King"

      min_count?(card_info, 20, [
        "Cleric of An'she",
        "Deafen",
        "Mistress of Mixtures",
        "Shadowtouched Kvaldir",
        "Shard of the Naaru",
        "The Light! It Burns!",
        "Astalor Bloodsworn",
        "Auchenai Phantasm",
        "City Tax",
        "Hi Ho Silverwing",
        "Hidden Gem",
        "Serena Bloodfeather",
        "Benevolent Banker",
        "Dehydrate",
        "Devouring Plague",
        "Haunting Nightmare",
        "Holy Nova",
        "Wickerflame Burnbristle",
        "Brittlebone Destroyer",
        "Fight Over Me",
        "Hysteria",
        "Ivory Knight",
        "School Teacher",
        "Xyrella",
        "Crystal Stag",
        "Mass Hysteria",
        "Raza the Chained",
        "Sandhoof Waterbearer",
        "Harmonic Pop",
        "Khartut Defender",
        "Lightshower Elemental",
        "Aman'Thul",
        "Blackwater Behemoth",
        "Blightblood Berserker",
        "Soul Mirror"
      ]) ->
        :Xyrella

      min_count?(card_info, 20, [
        "Backstab",
        "Blackwater Cutlass",
        "Bloodsail Flybooter",
        "Dig For Treasure",
        "Execute",
        "Gone Fishin'",
        "Jolly Roger",
        "Patches the Pirate",
        "Shiver Their Timbers!",
        "Sky Raider",
        "Swashburglar",
        "Amalgam of the Deep",
        "Bloodsail Raider",
        "Eviscerate",
        "Fan of Knives",
        "Fogsail Freebooter",
        "Harbor Scamp",
        "Obsidiansmith",
        "Parachute Brigand",
        "Serrated Bone Spike",
        "Toy Boat",
        "Ancharrr",
        "Bargain Bin Buccaneer",
        "Crow's Nest Lookout",
        "Defias Cannoneer",
        "Pufferfist",
        "Skybarge",
        "Swordfish",
        "Edwin, Defias Kingpin",
        "Hoard Pillager",
        "Sword Eater",
        "Bootstrap Sunkeneer",
        "Cannon Barrage",
        "Mr. Smite",
        "Pirate Admiral Hooktusk"
      ]) ->
        :"Patches the Pirate"

      min_count?(card_info, 20, [
        "Adaptation",
        "Embalming Ritual",
        "Grimscale Chum",
        "Grimscale Oracle",
        "Imprisoned Sungill",
        "Murloc Growfin",
        "Murloc Tidecaller",
        "Murmy",
        "Sir Finley, Sea Guide",
        "Spawnpool Forager",
        "Toxfin",
        "Unite the Murlocs",
        "Amalgam of the Deep",
        "Auctionhouse Gavel",
        "Hand of A'dal",
        "Hydrologist",
        "Lushwater Murcenary",
        "Murgur Murgurgle",
        "Primalfin Lookout",
        "Rockpool Hunter",
        "South Coast Chieftain",
        "Underbelly Angler",
        "Voidgill",
        "Bloodscent Vilefin",
        "Clownfish",
        "Coldlight Seer",
        "Consecration",
        "Cookie the Cook",
        "Murloc Warleader",
        "Nofin Can Stop Us",
        "Underlight Angling Rod",
        "Gentle Megasaur",
        "Murloc Knight",
        "Rotgill",
        "Everyfin is Awesome"
      ]) ->
        :"Sir Finley Mrrgglton"

      min_count?(card_info, 20, [
        "Ricochet Shot",
        "Tracking",
        "Urchin Spines",
        "Wound Prey",
        "Barrel of Monkeys",
        "Bola Shot",
        "Call Pet",
        "Fetch!",
        "Grievous Bite",
        "Rapid Fire",
        "Tame Beast (Rank 1)",
        "Animal Companion",
        "Master's Call",
        "Powershot",
        "Revive Pet",
        "Shellshot",
        "Swipe",
        "Unleash the Hounds",
        "Flanking Strike",
        "Marked Shot",
        "Swamp King Dred",
        "Amani War Bear",
        "Blackwater Behemoth",
        "Colaque",
        "Druid of the Plains",
        "Hydralodon",
        "King Mosh",
        "Toyrannosaurus",
        "Winged Guardian",
        "King Krush",
        "Oondasta",
        "Trenchstalker",
        "Banjosaur",
        "Tyrantus",
        "Shirvallah, the Tiger"
      ]) ->
        :"King Krush"

      min_count?(card_info, 18, [
        "Aquatic Form",
        "Innervate",
        "Preparation",
        "Forest Seedlings",
        "Mark of the Lotus",
        "Nature Studies",
        "Sow the Soil",
        "Witchwood Apple",
        "Lunar Eclipse",
        "Malfunction",
        "Mark of Scorn",
        "Natural Causes",
        "Fungal Fortunes",
        "Landscaping",
        "Overgrown Beanstalk",
        "Plot of Sin",
        "Soul of the Forest",
        "Fel'dorei Warband",
        "Aeroponics",
        "Arbor Up",
        "Deal with a Devil",
        "Living Mana",
        "Manufacturing Error",
        "Refreshing Spring Water",
        "Runic Carvings",
        "To My Side!",
        "Unending Swarm",
        "Drum Circle",
        "Rhok'delar",
        "Cultivation"
      ]) ->
        :"Forest Warden Omu"

      min_count?(card_info, 27, [
        "Drone Deconstructor",
        "Execute",
        "Glow-Tron",
        "Omega Assembly",
        "Trench Surveyor",
        "Amalgam of the Deep",
        "Bomb Toss",
        "From the Scrapheap",
        "Micro Mummy",
        "Noble Minibot",
        "Security Automaton",
        "Venomizer",
        "Bellowing Flames",
        "Coldlight Oracle",
        "Gorillabot A-3",
        "Mecha-Shark",
        "Mimiron, the Mastermind",
        "Powermace",
        "Seascout Operator",
        "Sky Claw",
        "SN1P-SN4P",
        "SP-3Y3-D3R",
        "Spider Bomb",
        "Ursatron",
        "Giggling Toymaker",
        "Outrider's Axe",
        "Pozzik, Audio Engineer",
        "Tiny Worldbreaker",
        "Brawl",
        "Dyn-o-matic",
        "Fireworker",
        "Zilliax",
        "Flame Behemoth",
        "Mothership",
        "V-07-TR-0N Prime",
        "Blastmaster Boom",
        "Boommaster Flark",
        "The Leviathan",
        "Gaia, the Techtonic",
        "Inventor Boom"
      ]) ->
        :"Dr. Boom"

      min_count?(card_info, 27, [
        "Blackjack Stunner",
        "Costumed Singer",
        "Secretkeeper",
        "Arcane Flakmage",
        "Bait and Switch",
        "Bargain Bin",
        "Cat Trick",
        "Explosive Trap",
        "Freezing Trap",
        "Hidden Meaning",
        "Hydrologist",
        "Ice Trap",
        "Mad Scientist",
        "Medivh's Valet",
        "Phase Stalker",
        "Quick Shot",
        "Snipe",
        "Sword of the Fallen",
        "Wandering Monster",
        "ZOMBEEEES!!!",
        "Cloaked Huntress",
        "Commander Rhyssa",
        "Inconspicuous Rider",
        "Petting Zoo",
        "Sparkjoy Cheat",
        "Chatty Bartender",
        "Throw Glaive",
        "Apexis Smuggler",
        "Halkias",
        "Orion, Mansion Manager",
        "Professor Putricide",
        "Spring the Trap",
        "Cannonmaster Smythe",
        "Lesser Emerald Spellstone",
        "Product 9",
        "Aggramar, the Avenger",
        "Contract Conjurer",
        "Sayge, Seer of Darkmoon",
        "Starstrung Bow",
        "King Plush"
      ]) ->
        :"Zul'jin"

      min_count?(card_info, 26, [
        "Batty Guest",
        "Call of the Grave",
        "Lingering Zombie",
        "Play Dead",
        "Unstable Felbolt",
        "Dead Ringer",
        "Defile",
        "Kindly Grandmother",
        "Loot Hoarder",
        "Museum Curator",
        "Roll the Bones",
        "Shallow Grave",
        "Starscryer",
        "Terrorscale Stalker",
        "Unstable Shadow Blast",
        "Devouring Ectoplasm",
        "Domino Effect",
        "Necrium Blade",
        "Piggyback Imp",
        "Reefwalker",
        "Voodoo Doll",
        "Ball Hog",
        "Baron Rivendare",
        "Infested Tauren",
        "Piloted Shredder",
        "Stubborn Suspect",
        "Teacher's Pet",
        "Vectus",
        "Claw Machine",
        "Ring Matron",
        "Darkmoon Tonk",
        "Enhanced Dreadlord",
        "Wretched Queen",
        "Obsidian Statue",
        "Stoneborn General"
      ]) ->
        :"N'Zoth, the Corruptor"

      min_count?(card_info, 30, [
        "Alleycat",
        "Blazing Invocation",
        "Mystery Winner",
        "Overwhelm",
        "Shock Hopper",
        "Slam",
        "Tracking",
        "Trinket Tracker",
        "Auctionhouse Gavel",
        "Crackling Razormaw",
        "Deeprun Engineer",
        "EVIL Cable Rat",
        "Grimestreet Informant",
        "Maze Guide",
        "Novice Engineer",
        "Painted Canvasaur",
        "Shrubadier",
        "Waxmancy",
        "Brilliant Macaw",
        "Crow's Nest Lookout",
        "Fairy Tale Forest",
        "Harmonica Soloist",
        "Kobold Apprentice",
        "Sewer Crawler",
        "Stitched Tracker",
        "Crud Caretaker",
        "Fire Plume Phoenix",
        "Rattling Rascal",
        "Triplewick Trickster",
        "Bomb Squad",
        "Cattle Rustler",
        "Dyn-o-matic",
        "Former Champ",
        "Loatheb",
        "Night Elf Huntress",
        "Abyssal Summoner",
        "Entitled Customer",
        "Lord Godfrey",
        "Swampqueen Hagatha",
        "Deathwing, Mad Aspect",
        "Gigafin",
        "Jepetto Joybuzz",
        "Murozond the Infinite",
        "Tidal Revenant",
        "Alexstrasza the Life-Binder"
      ]) ->
        :"Brann Bronzebeard"

      min_count?(card_info, 27, [
        "Aquatic Form",
        "Pounce",
        "Battlefiend",
        "Burning Heart",
        "Feast and Famine",
        "Jolly Roger",
        "Lesser Jasper Spellstone",
        "Secure the Deck",
        "Sock Puppet Slitherspear",
        "Toxic Reinforcements",
        "Battleworn Vanguard",
        "Crooked Cook",
        "Deathmatch Pavilion",
        "Felfire Deadeye",
        "Lesser Opal Spellstone",
        "Manafeeder Panthara",
        "Multi-Strike",
        "Papercraft Angel",
        "Rake",
        "Savage Striker",
        "Stoneskin Armorer",
        "Wickerclaw",
        "Defias Cannoneer",
        "Hookfist-3000",
        "Ironclad",
        "Keeneye Spotter",
        "Pufferfist",
        "Silithid Swarmer",
        "Dragonbane",
        "Glaiveshark",
        "Going Down Swinging",
        "Park Panther",
        "Sand Art Elemental",
        "Savage Combatant",
        "Shockspitter",
        "Spread the Word",
        "Captain Galvangar",
        "Khaz'goroth",
        "Confessor Paletress",
        "Frost Giant"
      ]) ->
        :"Guff Runetotem"

      min_count?(card_info, 20, [
        "Howling Blast",
        "Plague Strike",
        "Death Strike",
        "Frost Strike",
        "Heart Strike",
        "Patchwerk",
        "Defrost",
        "Meat Grinder",
        "Graveyard Shift",
        "Vicious Bloodworm",
        "Body Bagger",
        "Harbinger of Winter",
        "Bone Breaker",
        "Stitched Giant",
        "Obliterate",
        "Bonedigger Geist",
        "Thassarian",
        "Blightfang",
        "Hardcore Cultist",
        "Climactic Necrotic Explosion",
        "The Primus",
        "Pile of Bones",
        "Fistful of Corpses",
        "Harrowing Ox",
        "Maw and Paw",
        "Crop Rotation",
        "Reska, the Pit Boss",
        "Mining Casualties",
        "Arthas's Gift",
        "Quartzite Crusher",
        "Rainbow Seamstress",
        "Threads of Despair",
        "Hematurge",
        "Necrotic Mortician",
        "Soulbreaker"
      ]) ->
        :Arfus

      min_count?(card_info, 19, [
        "Archmage Vargoth",
        "Chaos Creation",
        "Chaos Strike",
        "Coordinated Strike",
        "Demonic Assault",
        "Disciple of Argus",
        "Dryscale Deputy",
        "Expendable Performers",
        "Fan the Hammer",
        "Fel Barrage",
        "Fossil Fanatic",
        "Grave Defiler",
        "Herald of Chaos",
        "Impfestation",
        "Jace Darkweaver",
        "Jotun, the Eternal",
        "Metamorphosis",
        "Multi-Strike",
        "Queen Azshara",
        "Quick Pick",
        "Sigil of Time",
        "Stargazer Luna",
        "Taste of Chaos"
      ]) ->
        :"Illidan Stormrage"

      min_count?(card_info, 31, [
        "Synthesize",
        "Horn of the Windlord",
        "Flame Geyser",
        "Elemental Allies",
        "Sandstorm Elemental",
        "Kalimos, Primal Lord",
        "Al'ar",
        "Fire Fly",
        "Therazane",
        "Kindling Elemental",
        "Siamat",
        "Menacing Nimbus",
        "Spotlight",
        "Minecart Cruiser",
        "Arid Stormer",
        "Elementary Reaction",
        "Waxadred",
        "Elemental Evocation",
        "Skarr, the Catastrophe",
        "Wailing Vapor",
        "Tainted Remnant",
        "Aqua Archivist",
        "Al'Akir the Windlord",
        "Baron Geddon",
        "Frostfin Chomper",
        "Dang-Blasted Elemental",
        "Ragnaros the Firelord",
        "Baking Soda Volcano",
        "Trusty Companion",
        "Lightning Storm",
        "Lilypad Lurker",
        "Gyreworm",
        "Sleetbreaker",
        "Mes'Adune the Fractured",
        "Devolving Missiles"
      ]) ->
        :Thrall

      min_count?(card_info, 31, [
        "Blessing of Wisdom",
        "Acolyte of Pain",
        "Warsong Commander",
        "Stargazer Luna",
        "Knife Juggler",
        "Keeper's Strength",
        "Hi Ho Silverwing",
        "Crooked Cook",
        "Hand of A'dal",
        "Funkfin",
        "Goody Two-Shields",
        "Argent Protector",
        "Crusader Aura",
        "Divine Favor",
        "First Day of School",
        "Sound the Bells!",
        "Blood Matriarch Liadrin",
        "Magnifying Glaive",
        "Knight of Anointment",
        "Manafeeder Panthara",
        "Consecration",
        "Salhet's Pride",
        "Wickerflame Burnbristle",
        "Ancestral Guardian",
        "Disco Maul",
        "Sanguine Soldier",
        "Alliance Bannerman",
        "Hydrologist",
        "Hammer of Wrath",
        "Keeper of Uldaman",
        "For Quel'Thalas!",
        "Cathedral of Atonement",
        "Aldor Peacekeeper",
        "Voracious Reader",
        "Squashling"
      ]) ->
        :"Uther Lightbringer"

      min_count?(card_info, 41, [
        "Synthesize",
        "Prismatic Elemental",
        "Astral Rift",
        "Violet Spellwing",
        "Dryscale Deputy",
        "Messenger Raven",
        "Reckless Diretroll",
        "Spawn of Deathwing",
        "First Flame",
        "Fire Fly",
        "Ram Commander",
        "Trolley Problem",
        "Ravencaller",
        "Wandmaker",
        "Whelp Wrangler",
        "Leyline Manipulator",
        "Mana Cyclone",
        "Dark Peddler",
        "First Day of School",
        "Maruut Stonebinder",
        "Tiny Knight of Evil",
        "Unstable Portal",
        "Mana Giant",
        "Magic Trick",
        "School Teacher",
        "Instructor Fireheart",
        "Dark Skies",
        "Cho'gall",
        "Expired Merchant",
        "Unstable Felbolt",
        "Jar Dealer",
        "Flint Firearm",
        "Evocation",
        "Gloomstone Guardian",
        "Training Session",
        "Cobalt Spellkin",
        "Arcane Wyrm",
        "Babbling Book",
        "Runed Orb",
        "Blast Wave",
        "Wand Thief",
        "Primordial Glyph",
        "Learn Draconic",
        "Arcsplitter",
        "Grand Magister Rommath"
      ]) ->
        :"Jaina Proudmoore"

      min_count?(card_info, 26, [
        "Ancient Shieldbearer",
        "BEEEES!!!",
        "Branching Paths",
        "Cactus Construct",
        "Chaotic Consumption",
        "Darkshire Councilman",
        "Dreamway Guardians",
        "Flipper Friends",
        "Forest Seedlings",
        "Frostwolf Kennels",
        "Glowfly Swarm",
        "Grimoire of Sacrifice",
        "Haunted Creeper",
        "Imp Gang Boss",
        "Klaxxi Amber-Weaver",
        "Lingering Zombie",
        "Living Roots",
        "Mining Casualties",
        "Murlocula",
        "Plague of Flames",
        "Plot of Sin",
        "Pop-Up Book",
        "Shrubadier",
        "Swarm of Lightbugs",
        "Swipe",
        "Thorngrowth Sentries",
        "Trial by Fire",
        "Twilight Darkmender",
        "Twin Emperor Vek'lor",
        "Wicked Shipment"
      ]) ->
        :"Malfurion Stormrage"

      min_count?(card_info, 17, [
        "Acolyte of Death",
        "Arms Dealer",
        "Body Bagger",
        "Corpse Bride",
        "Corpse Farm",
        "Crop Rotation",
        "Eulogizer",
        "Fistful of Corpses",
        "Haunted Creeper",
        "Heart Strike",
        "Lingering Zombie",
        "Malignant Horror",
        "Mining Casualties",
        "Plagued Grain",
        "Runes of Darkness",
        "Sickly Grimewalker",
        "Stitched Giant",
        "The Scourge",
        "Tomb Guardians",
        "Unliving Champion",
        "Ymirjar Deathbringer"
      ]) ->
        :"The Lich King"

      min_count?(card_info, 31, [
        "Cleric of An'she",
        "Devouring Plague",
        "Xyrella",
        "Shard of the Naaru",
        "Hysteria",
        "Haunting Nightmare",
        "Blightblood Berserker",
        "Soul Mirror",
        "Hi Ho Silverwing",
        "Hidden Gem",
        "Deafen",
        "Fight Over Me",
        "Raza the Chained",
        "Dehydrate",
        "Blackwater Behemoth",
        "Aman'Thul",
        "Lightshower Elemental",
        "Khartut Defender",
        "City Tax",
        "School Teacher",
        "Mistress of Mixtures",
        "Shadowtouched Kvaldir",
        "The Light! It Burns!",
        "Holy Nova",
        "Wickerflame Burnbristle",
        "Benevolent Banker",
        "Crystal Stag",
        "Sandhoof Waterbearer",
        "Auchenai Phantasm",
        "Serena Bloodfeather",
        "Brittlebone Destroyer",
        "Mass Hysteria",
        "Harmonic Pop",
        "Ivory Knight",
        "Astalor Bloodsworn"
      ]) ->
        :"Anduin Wrynn"

      min_count?(card_info, 31, [
        "Bloodsail Raider",
        "Sky Raider",
        "Jolly Roger",
        "Fan of Knives",
        "Bootstrap Sunkeneer",
        "Amalgam of the Deep",
        "Bargain Bin Buccaneer",
        "Cannon Barrage",
        "Ancharrr",
        "Backstab",
        "Fogsail Freebooter",
        "Pufferfist",
        "Edwin, Defias Kingpin",
        "Toy Boat",
        "Mr. Smite",
        "Gone Fishin'",
        "Obsidiansmith",
        "Shiver Their Timbers!",
        "Dig for Treasure",
        "Crow's Nest Lookout",
        "Sword Eater",
        "Bloodsail Flybooter",
        "Pirate Admiral Hooktusk",
        "Defias Cannoneer",
        "Hoard Pillager",
        "Swashburglar",
        "Parachute Brigand",
        "Blackwater Cutlass",
        "Harbor Scamp",
        "Eviscerate",
        "Skybarge",
        "Execute",
        "Serrated Bone Spike",
        "Patches the Pirate",
        "Swordfish"
      ]) ->
        :"Valeera Sanguinar"

      min_count?(card_info, 31, [
        "Shirvallah, the Tiger",
        "Marked Shot",
        "Tracking",
        "Druid of the Plains",
        "Call Pet",
        "Blackwater Behemoth",
        "Wound Prey",
        "Winged Guardian",
        "Master's Call",
        "Tyrantus",
        "Unleash the Hounds",
        "Swamp King Dred",
        "Banjosaur",
        "Revive Pet",
        "Toyrannosaurus",
        "Bola Shot",
        "Rapid Fire",
        "Colaque",
        "Powershot",
        "Grievous Bite",
        "Tame Beast (Rank 1)",
        "Animal Companion",
        "Flanking Strike",
        "Ricochet Shot",
        "King Krush",
        "Amani War Bear",
        "Oondasta",
        "Urchin Spines",
        "Swipe",
        "Shellshot",
        "Trenchstalker",
        "Fetch!",
        "King Mosh",
        "Hydralodon",
        "Barrel of Monkeys"
      ]) ->
        :Rexxar

      min_count?(card_info, 26, [
        "Aeroponics",
        "Aquatic Form",
        "Arbor Up",
        "Cultivation",
        "Deal with a Devil",
        "Drum Circle",
        "Fel'dorei Warband",
        "Forest Seedlings",
        "Fungal Fortunes",
        "Innervate",
        "Landscaping",
        "Living Mana",
        "Lunar Eclipse",
        "Malfunction",
        "Manufacturing Error",
        "Mark of Scorn",
        "Mark of the Lotus",
        "Natural Causes",
        "Nature Studies",
        "Overgrown Beanstalk",
        "Plot of Sin",
        "Preparation",
        "Refreshing Spring Water",
        "Rhok'delar",
        "Runic Carvings",
        "Soul of the Forest",
        "Sow the Soil",
        "To My Side!",
        "Unending Swarm",
        "Witchwood Apple"
      ]) ->
        :"Malfurion Stormrage"

      min_count?(card_info, 36, [
        "Blastmaster Boom",
        "Outrider's Axe",
        "Venomizer",
        "Coldlight Oracle",
        "Flame Behemoth",
        "Bomb Toss",
        "Zilliax",
        "Amalgam of the Deep",
        "Giggling Toymaker",
        "Omega Assembly",
        "Fireworker",
        "SN1P-SN4P",
        "Brawl",
        "Trench Surveyor",
        "Powermace",
        "The Leviathan",
        "Noble Minibot",
        "Spider Bomb",
        "Mimiron, the Mastermind",
        "Mothership",
        "Dyn-o-matic",
        "Gaia, the Techtonic",
        "Pozzik, Audio Engineer",
        "Seascout Operator",
        "Inventor Boom",
        "From the Scrapheap",
        "Mecha-Shark",
        "Gorillabot A-3",
        "Security Automaton",
        "V-07-TR-0N Prime",
        "Drone Deconstructor",
        "Boommaster Flark",
        "Sky Claw",
        "Tiny Worldbreaker",
        "Micro Mummy",
        "Execute",
        "SP-3Y3-D3R",
        "Glow-Tron",
        "Bellowing Flames",
        "Ursatron"
      ]) ->
        :"Garrosh Hellscream"

      min_count?(card_info, 36, [
        "Commander Rhyssa",
        "Sayge, Seer of Darkmoon",
        "Ice Trap",
        "Petting Zoo",
        "Snipe",
        "Medivh's Valet",
        "Bargain Bin",
        "ZOMBEEEES!!!",
        "Apexis Smuggler",
        "Starstrung Bow",
        "Hidden Meaning",
        "Sparkjoy Cheat",
        "Cannonmaster Smythe",
        "Lesser Emerald Spellstone",
        "Aggramar, the Avenger",
        "Contract Conjurer",
        "Cloaked Huntress",
        "Costumed Singer",
        "Chatty Bartender",
        "Cat Trick",
        "Mad Scientist",
        "Throw Glaive",
        "Professor Putricide",
        "Sword of the Fallen",
        "Spring the Trap",
        "Inconspicuous Rider",
        "Product 9",
        "Blackjack Stunner",
        "Halkias",
        "Bait and Switch",
        "Wandering Monster",
        "King Plush",
        "Hydrologist",
        "Explosive Trap",
        "Arcane Flakmage",
        "Quick Shot",
        "Secretkeeper",
        "Freezing Trap",
        "Phase Stalker",
        "Orion, Mansion Manager"
      ]) ->
        :Rexxar

      min_count?(card_info, 31, [
        "Play Dead",
        "Kindly Grandmother",
        "Devouring Ectoplasm",
        "Museum Curator",
        "Starscryer",
        "Piggyback Imp",
        "Domino Effect",
        "Terrorscale Stalker",
        "Defile",
        "Stubborn Suspect",
        "Ball Hog",
        "Lingering Zombie",
        "Enhanced Dreadlord",
        "Roll the Bones",
        "Obsidian Statue",
        "Stoneborn General",
        "Vectus",
        "Wretched Queen",
        "Reefwalker",
        "Baron Rivendare",
        "Shallow Grave",
        "Unstable Felbolt",
        "Infested Tauren",
        "Unstable Shadow Blast",
        "Darkmoon Tonk",
        "Voodoo Doll",
        "Necrium Blade",
        "Ring Matron",
        "Dead Ringer",
        "Loot Hoarder",
        "Claw Machine",
        "Batty Guest",
        "Call of the Grave",
        "Piloted Shredder",
        "Teacher's Pet"
      ]) ->
        :"Gul'dan"

      min_count?(card_info, 41, [
        "Overwhelm",
        "Fairy Tale Forest",
        "Cattle Rustler",
        "Sewer Crawler",
        "Lord Godfrey",
        "Stitched Tracker",
        "Loatheb",
        "Former Champ",
        "Rattling Rascal",
        "Blazing Invocation",
        "Gigafin",
        "Tracking",
        "Tidal Revenant",
        "Maze Guide",
        "Slam",
        "EVIL Cable Rat",
        "Deeprun Engineer",
        "Harmonica Soloist",
        "Shrubadier",
        "Painted Canvasaur",
        "Deathwing, Mad Aspect",
        "Waxmancy",
        "Novice Engineer",
        "Kobold Apprentice",
        "Bomb Squad",
        "Dyn-o-matic",
        "Swampqueen Hagatha",
        "Alexstrasza the Life-Binder",
        "Crow's Nest Lookout",
        "Alleycat",
        "Jepetto Joybuzz",
        "Crackling Razormaw",
        "Fire Plume Phoenix",
        "Shock Hopper",
        "Auctionhouse Gavel",
        "Mystery Winner",
        "Brilliant Macaw",
        "Trinket Tracker",
        "Abyssal Summoner",
        "Murozond the Infinite",
        "Entitled Customer",
        "Grimestreet Informant",
        "Night Elf Huntress",
        "Crud Caretaker",
        "Triplewick Trickster"
      ]) ->
        :Rexxar

      min_count?(card_info, 36, [
        "Dragonbane",
        "Wickerclaw",
        "Shockspitter",
        "Deathmatch Pavilion",
        "Lesser Opal Spellstone",
        "Confessor Paletress",
        "Jolly Roger",
        "Crooked Cook",
        "Frost Giant",
        "Aquatic Form",
        "Secure the Deck",
        "Savage Combatant",
        "Toxic Reinforcements",
        "Hookfist-3000",
        "Pufferfist",
        "Papercraft Angel",
        "Ironclad",
        "Savage Striker",
        "Stoneskin Armorer",
        "Burning Heart",
        "Lesser Jasper Spellstone",
        "Felfire Deadeye",
        "Sock Puppet Slitherspear",
        "Rake",
        "Manafeeder Panthara",
        "Pounce",
        "Sand Art Elemental",
        "Multi-Strike",
        "Silithid Swarmer",
        "Defias Cannoneer",
        "Keeneye Spotter",
        "Feast and Famine",
        "Battlefiend",
        "Glaiveshark",
        "Going Down Swinging",
        "Spread the Word",
        "Park Panther",
        "Battleworn Vanguard",
        "Captain Galvangar",
        "Khaz'goroth"
      ]) ->
        :"Malfurion Stormrage"

      min_count?(card_info, 31, [
        "Lor'themar Theron",
        "Loatheb",
        "Sir Finley, Sea Guide",
        "Zilliax",
        "Flightmaster Dungar",
        "Ivus, the Forest Lord",
        "Siamat",
        "Moonfang",
        "Overlord Runthak",
        "SN1P-SN4P",
        "Neptulon the Tidehunter",
        "Goliath, Sneed's Masterpiece",
        "Mankrik",
        "Maiev Shadowsong",
        "Brightwing",
        "Bloodmage Thalnos",
        "Raid Boss Onyxia",
        "Cairne Bloodhoof",
        "Gnomelia, S.A.F.E. Pilot",
        "Alexstrasza the Life-Binder",
        "Pozzik, Audio Engineer",
        "Jepetto Joybuzz",
        "Mutanus the Devourer",
        "Flint Firearm",
        "Yogg-Saron, Unleashed",
        "Archdruid Naralex",
        "Brann Bronzebeard",
        "Blademaster Okani",
        "Korrak the Bloodrager",
        "Ozumat",
        "Dr. Boom",
        "Emperor Thaurissan",
        "Sylvanas Windrunner",
        "Astalor Bloodsworn",
        "Sphere of Sapience"
      ]) ->
        :"Gul'dan"

      min_count?(card_info, 31, [
        "Stitched Giant",
        "Frost Strike",
        "Soulbreaker",
        "Plague Strike",
        "Harbinger of Winter",
        "Necrotic Mortician",
        "Reska, the Pit Boss",
        "Meat Grinder",
        "Body Bagger",
        "Howling Blast",
        "Arthas's Gift",
        "Death Strike",
        "Threads of Despair",
        "Fistful of Corpses",
        "Climactic Necrotic Explosion",
        "Rainbow Seamstress",
        "Thassarian",
        "Hematurge",
        "Bone Breaker",
        "Graveyard Shift",
        "Vicious Bloodworm",
        "Patchwerk",
        "Crop Rotation",
        "Harrowing Ox",
        "Maw and Paw",
        "Pile of Bones",
        "Blightfang",
        "Hardcore Cultist",
        "Defrost",
        "Heart Strike",
        "Bonedigger Geist",
        "Quartzite Crusher",
        "Obliterate",
        "The Primus",
        "Mining Casualties"
      ]) ->
        :"The Lich King"

      min_count?(card_info, 31, [
        "Embalming Ritual",
        "Underlight Angling Rod",
        "Murgur Murgurgle",
        "Coldlight Seer",
        "Unite the Murlocs",
        "Sir Finley, Sea Guide",
        "Grimscale Oracle",
        "Gentle Megasaur",
        "Amalgam of the Deep",
        "Clownfish",
        "Hand of A'dal",
        "Voidgill",
        "Adaptation",
        "Toxfin",
        "Lushwater Murcenary",
        "Primalfin Lookout",
        "Nofin Can Stop Us",
        "Murloc Tidecaller",
        "South Coast Chieftain",
        "Rotgill",
        "Murmy",
        "Underbelly Angler",
        "Consecration",
        "Imprisoned Sungill",
        "Murloc Warleader",
        "Auctionhouse Gavel",
        "Murloc Growfin",
        "Everyfin is Awesome",
        "Hydrologist",
        "Rockpool Hunter",
        "Spawnpool Forager",
        "Grimscale Chum",
        "Bloodscent Vilefin",
        "Cookie the Cook",
        "Murloc Knight"
      ]) ->
        :"Uther Lightbringer"

      min_count?(card_info, 41, [
        "Nether Breath",
        "Wyrmrest Agent",
        "Nithogg",
        "Lay Down the Law",
        "Lightning Breath",
        "Onyxian Warder",
        "Breath of Dreams",
        "Malygos, Aspect of Magic",
        "Arcane Breath",
        "Twilight Whelp",
        "Flight of the Bronze",
        "Candle Breath",
        "Netherspite Historian",
        "Molten Breath",
        "Firetree Witchdoctor",
        "Murozond, Thief of Time",
        "Crazed Netherwing",
        "Dragonfire Potion",
        "Sand Breath",
        "Blackwing Corruptor",
        "Breath of the Infinite",
        "Alexstrasza's Champion",
        "Redscale Dragontamer",
        "Dragonrider Talritha",
        "Giftwrapped Whelp",
        "Raid Boss Onyxia",
        "Deathwing, Mad Aspect",
        "Chronobreaker",
        "Anachronos",
        "Corrosive Breath",
        "Lightbringer's Hammer",
        "Alexstrasza the Life-Binder",
        "Consecration",
        "Duskbreaker",
        "Cleric of Scales",
        "Splish-Splash Whelp",
        "Aeon Reaver",
        "Desert Nestmatron",
        "Timewarden",
        "Future Emissary",
        "Amber Whelp",
        "Murozond the Infinite",
        "Dragonmaw Sentinel",
        "Ysera the Dreamer",
        "Fye, the Setting Sun"
      ]) ->
        :"Uther Lightbringer"

      min_count?(card_info, 26, [
        "Aerosoilizer",
        "BEEEES!!!",
        "Cactus Construct",
        "Chaotic Consumption",
        "Darkshire Councilman",
        "Doomcaller",
        "Dreamway Guardians",
        "Embers of Strength",
        "Eyestalk of C'Thun",
        "Flipper Friends",
        "Grimoire of Sacrifice",
        "Haunted Creeper",
        "Lingering Zombie",
        "Living Roots",
        "Lunar Eclipse",
        "Mark of the Lotus",
        "Mining Casualties",
        "Murlocula",
        "Plague of Flames",
        "Plot of Sin",
        "Pop-Up Book",
        "Saddle Up!",
        "Scale of Onyxia",
        "Shrubadier",
        "Sneaky Snakes",
        "Spreading Plague",
        "Swarm of Lightbugs",
        "Swipe",
        "Trial by Fire",
        "Wolpertinger"
      ]) ->
        :"Malfurion Stormrage"

      min_count?(card_info, 36, [
        "Blastmaster Boom",
        "Coldlight Oracle",
        "Flame Behemoth",
        "Bomb Toss",
        "Amalgam of the Deep",
        "Giggling Toymaker",
        "General Vezax",
        "Fireworker",
        "SN1P-SN4P",
        "Explodinator",
        "Reckless Flurry",
        "Harvest Golem",
        "Kodohide Drumkit",
        "Trench Surveyor",
        "Mecharoo",
        "Shield Block",
        "The Leviathan",
        "Shield Shatter",
        "Mimiron, the Mastermind",
        "Mothership",
        "Dyn-o-matic",
        "Gaia, the Techtonic",
        "Seascout Operator",
        "Inventor Boom",
        "Heavy Plate",
        "Part Scrapper",
        "From the Scrapheap",
        "Mecha-Shark",
        "Security Automaton",
        "V-07-TR-0N Prime",
        "Bash",
        "Shotbot",
        "Ferocious Howl",
        "Drone Deconstructor",
        "Boommaster Flark",
        "Sky Claw",
        "Microtech Controller",
        "Micro Mummy",
        "Replicating Menace",
        "Shield Slam"
      ]) ->
        :"Garrosh Hellscream"

      min_count?(card_info, 31, [
        "Frost Strike",
        "Soulbreaker",
        "Plague Strike",
        "Reska, the Pit Boss",
        "Howling Blast",
        "Arthas's Gift",
        "Death Strike",
        "Threads of Despair",
        "Remorseless Winter",
        "Anti-Magic Shell",
        "Harmonic Metal",
        "Fistful of Corpses",
        "Mechagnome Guide",
        "Down with the Ship",
        "Rainbow Seamstress",
        "Runes of Darkness",
        "Venomous Scorpid",
        "Card Grader",
        "Frozen Over",
        "Bone Breaker",
        "Graveyard Shift",
        "Crop Rotation",
        "Pandaren Importer",
        "Chittering Tunneler",
        "Blightfang",
        "Glacial Advance",
        "Benevolent Banker",
        "Defrost",
        "Heart Strike",
        "Quartzite Crusher",
        "Obliterate",
        "Marshspawn",
        "The Primus",
        "Unholy Frenzy",
        "Spellcoiler"
      ]) ->
        :"The Lich King"

      min_count?(card_info, 46, [
        "Synthesize",
        "Prismatic Elemental",
        "Astral Rift",
        "Scarab Keychain",
        "Sinister Deal",
        "Violet Spellwing",
        "Dryscale Deputy",
        "Messenger Raven",
        "Reckless Diretroll",
        "Spawn of Deathwing",
        "First Flame",
        "Fire Fly",
        "Ram Commander",
        "Trolley Problem",
        "Ravencaller",
        "Whispers of EVIL",
        "Wandmaker",
        "Whelp Wrangler",
        "Leyline Manipulator",
        "Dark Peddler",
        "First Day of School",
        "Symphony of Sins",
        "Maruut Stonebinder",
        "Tiny Knight of Evil",
        "Unstable Portal",
        "Mana Giant",
        "Magic Trick",
        "School Teacher",
        "Instructor Fireheart",
        "Dark Skies",
        "Cho'gall",
        "Expired Merchant",
        "Unstable Felbolt",
        "Jar Dealer",
        "Flint Firearm",
        "Evocation",
        "Gloomstone Guardian",
        "Training Session",
        "Twisted Knowledge",
        "Cobalt Spellkin",
        "Arcane Wyrm",
        "Babbling Book",
        "Runed Orb",
        "Wand Thief",
        "Primordial Glyph",
        "Suspicious Peddler",
        "Learn Draconic",
        "Arcsplitter",
        "Marin the Manager",
        "Grand Magister Rommath"
      ]) ->
        :"Jaina Proudmoore"

      min_count?(card_info, 46, [
        "Nether Breath",
        "Wyrmrest Agent",
        "Nithogg",
        "Lay Down the Law",
        "Lightning Breath",
        "Onyxian Warder",
        "Breath of Dreams",
        "Malygos, Aspect of Magic",
        "Arcane Breath",
        "Twilight Whelp",
        "Flight of the Bronze",
        "Candle Breath",
        "Netherspite Historian",
        "Molten Breath",
        "Firetree Witchdoctor",
        "Murozond, Thief of Time",
        "Crazed Netherwing",
        "Dragonfire Potion",
        "Sand Breath",
        "Blackwing Corruptor",
        "Daring Drake",
        "Breath of the Infinite",
        "Crowd Roaster",
        "Alexstrasza's Champion",
        "Redscale Dragontamer",
        "Dragonrider Talritha",
        "Giftwrapped Whelp",
        "Chillmaw",
        "Raid Boss Onyxia",
        "Deathwing, Mad Aspect",
        "Chronobreaker",
        "Bronze Explorer",
        "Anachronos",
        "Corrosive Breath",
        "Lightbringer's Hammer",
        "Alexstrasza the Life-Binder",
        "Twilight Guardian",
        "Consecration",
        "Duskbreaker",
        "Cleric of Scales",
        "Splish-Splash Whelp",
        "Aeon Reaver",
        "Desert Nestmatron",
        "Timewarden",
        "Future Emissary",
        "Amber Whelp",
        "Murozond the Infinite",
        "Dragonmaw Sentinel",
        "Ysera the Dreamer",
        "Fye, the Setting Sun"
      ]) ->
        :"Uther Lightbringer"

      min_count?(card_info, 41, [
        "Commander Rhyssa",
        "Sayge, Seer of Darkmoon",
        "Ice Trap",
        "Petting Zoo",
        "Snipe",
        "Medivh's Valet",
        "Jandice Barov",
        "Bargain Bin",
        "ZOMBEEEES!!!",
        "Anonymous Informant",
        "Apexis Smuggler",
        "Starstrung Bow",
        "Hidden Meaning",
        "Sparkjoy Cheat",
        "Cannonmaster Smythe",
        "Lesser Emerald Spellstone",
        "Aggramar, the Avenger",
        "Contract Conjurer",
        "Harmonica Soloist",
        "Asvedon, the Grandshield",
        "Cloaked Huntress",
        "Costumed Singer",
        "Chatty Bartender",
        "Cat Trick",
        "Mad Scientist",
        "Scuttlebutt Ghoul",
        "Throw Glaive",
        "Professor Putricide",
        "Sword of the Fallen",
        "Spring the Trap",
        "Inconspicuous Rider",
        "Product 9",
        "Blackjack Stunner",
        "Halkias",
        "Bait and Switch",
        "Wandering Monster",
        "King Plush",
        "Hydrologist",
        "Explosive Trap",
        "Arcane Flakmage",
        "Quick Shot",
        "Secretkeeper",
        "Freezing Trap",
        "Phase Stalker",
        "Orion, Mansion Manager"
      ]) ->
        :Rexxar

      min_count?(card_info, 36, [
        "Synthesize",
        "Prismatic Elemental",
        "Horn of the Windlord",
        "Ragnaros, Lightlord",
        "Flame Geyser",
        "Elemental Allies",
        "Sandstorm Elemental",
        "Kalimos, Primal Lord",
        "Al'ar",
        "Fire Fly",
        "Kindling Elemental",
        "Siamat",
        "Menacing Nimbus",
        "Crystalline Oracle",
        "Spotlight",
        "Neptulon the Tidehunter",
        "Minecart Cruiser",
        "Arid Stormer",
        "Elementary Reaction",
        "Scorch",
        "Waxadred",
        "Skarr, the Catastrophe",
        "Wailing Vapor",
        "Tainted Remnant",
        "Aqua Archivist",
        "Overflow Surger",
        "Al'Akir the Windlord",
        "Baron Geddon",
        "Unchained Gladiator",
        "Dang-Blasted Elemental",
        "Ragnaros the Firelord",
        "Baking Soda Volcano",
        "Trusty Companion",
        "Lightning Storm",
        "Lilypad Lurker",
        "Gyreworm",
        "Sleetbreaker",
        "Eroded Sediment",
        "Mes'Adune the Fractured",
        "Devolving Missiles"
      ]) ->
        :Thrall

      min_count?(card_info, 31, [
        "Planted Evidence",
        "Overgrowth",
        "Shirvallah, the Tiger",
        "Nature Studies",
        "Cactus Construct",
        "The Lurker Below",
        "Invigorate",
        "Mythical Terror",
        "Tracking",
        "Mountain Bear",
        "Blackwater Behemoth",
        "Winged Guardian",
        "Master's Call",
        "Crabatoa",
        "Swamp King Dred",
        "Banjosaur",
        "Revive Pet",
        "Nellie, the Great Thresher",
        "Colaque",
        "Star Power",
        "Heat Wave",
        "Grievous Bite",
        "Tame Beast (Rank 1)",
        "Animal Companion",
        "Flanking Strike",
        "Oondasta",
        "King Plush",
        "Wild Growth",
        "Glugg the Gulper",
        "Swipe",
        "Shellshot",
        "Fetch!",
        "Ozumat",
        "Hydralodon",
        "Barrel of Monkeys"
      ]) ->
        :Rexxar

      min_count?(card_info, 20, [
        "Archmage Vargoth",
        "Chaos Creation",
        "Chaos Strike",
        "Coordinated Strike",
        "Demonic Assault",
        "Dryscale Deputy",
        "Electra Stormsurge",
        "Expendable Performers",
        "Fan the Hammer",
        "Fel Barrage",
        "Fossil Fanatic",
        "Grave Defiler",
        "Impfestation",
        "Jace Darkweaver",
        "Jotun, the Eternal",
        "Metamorphosis",
        "Multi-Strike",
        "Queen Azshara",
        "Quick Pick",
        "SECURITY!!",
        "Sigil of Time",
        "Stargazer Luna",
        "Taste of Chaos",
        "Zai, the Incredible"
      ]) ->
        :"Illidan Stormrage"

      min_count?(card_info, 31, [
        "Play Dead",
        "Kindly Grandmother",
        "Mindflayer Kaahrj",
        "Imported Tarantula",
        "Museum Curator",
        "Domino Effect",
        "Defile",
        "Stubborn Suspect",
        "Feign Death",
        "Lingering Zombie",
        "Bloated Python",
        "Mountain Bear",
        "Roll the Bones",
        "Obsidian Statue",
        "Nesting Golem",
        "Disciple of Argus",
        "N'Zoth, the Corruptor",
        "Life from Death",
        "Nerubian Egg",
        "Ravenous Kraken",
        "Greedy Sprite",
        "Mothership",
        "Baron Rivendare",
        "Shallow Grave",
        "Unstable Felbolt",
        "Unstable Shadow Blast",
        "Obsidian Revenant",
        "Darkmoon Tonk",
        "Coilfang Warlord",
        "Necrium Blade",
        "Loot Hoarder",
        "Korrak the Bloodrager",
        "Batty Guest",
        "Call of the Grave",
        "Teacher's Pet"
      ]) ->
        :"Gul'dan"

      min_count?(card_info, 31, [
        "Acolyte of Pain",
        "Warsong Commander",
        "Stargazer Luna",
        "Knife Juggler",
        "Keeper's Strength",
        "Onyx Bishop",
        "Hi Ho Silverwing",
        "Crooked Cook",
        "Hand of A'dal",
        "Funkfin",
        "Goody Two-Shields",
        "Rokara",
        "Argent Protector",
        "Crusader Aura",
        "First Day of School",
        "Sound the Bells!",
        "Blood Matriarch Liadrin",
        "Magnifying Glaive",
        "Knight of Anointment",
        "Manafeeder Panthara",
        "Consecration",
        "Salhet's Pride",
        "Wickerflame Burnbristle",
        "Ancestral Guardian",
        "Disco Maul",
        "Sanguine Soldier",
        "Alliance Bannerman",
        "Hydrologist",
        "Hammer of Wrath",
        "Keeper of Uldaman",
        "Cathedral of Atonement",
        "Aldor Peacekeeper",
        "Voracious Reader",
        "Power Word: Shield",
        "Squashling"
      ]) ->
        :"Uther Lightbringer"

      min_count?(card_info, 31, [
        "Planted Evidence",
        "Lightning Bloom",
        "Nature Studies",
        "Malfunction",
        "Refreshing Spring Water",
        "Witchwood Apple",
        "Living Mana",
        "Mark of the Lotus",
        "Arbor Up",
        "Manufacturing Error",
        "Overgrown Beanstalk",
        "Plot of Sin",
        "Rhok'delar",
        "Innervate",
        "Aeroponics",
        "To My Side!",
        "Lunar Eclipse",
        "Fungal Fortunes",
        "Unending Swarm",
        "Runic Carvings",
        "Cultivation",
        "Landscaping",
        "Flash of Lightning",
        "Poison Seeds",
        "Sow the Soil",
        "Convoke the Spirits",
        "Drum Circle",
        "Spot the Difference",
        "Mark of Scorn",
        "Deal with a Devil",
        "Fel'dorei Warband",
        "Forest Seedlings",
        "Natural Causes",
        "Soul of the Forest",
        "Lightning Reflexes"
      ]) ->
        :"Malfurion Stormrage"

      min_count?(card_info, 31, [
        "Overwhelm",
        "Fairy Tale Forest",
        "Prismatic Elemental",
        "Sewer Crawler",
        "Lord Godfrey",
        "Stitched Tracker",
        "Former Champ",
        "Street Sweeper",
        "Rattling Rascal",
        "Crystology",
        "Gigafin",
        "Tracking",
        "Tidal Revenant",
        "Maze Guide",
        "Slam",
        "Shrubadier",
        "Waxmancy",
        "Novice Engineer",
        "Kobold Apprentice",
        "Bomb Squad",
        "Dyn-o-matic",
        "Swampqueen Hagatha",
        "Alexstrasza the Life-Binder",
        "Crow's Nest Lookout",
        "Shock Hopper",
        "Auctionhouse Gavel",
        "Brilliant Macaw",
        "Trinket Tracker",
        "Abyssal Summoner",
        "Murozond the Infinite",
        "Entitled Customer",
        "Horseshoe Slinger",
        "Night Elf Huntress",
        "Crud Caretaker",
        "Triplewick Trickster"
      ]) ->
        :Rexxar

      min_count?(card_info, 31, [
        "Dragonbane",
        "Horn of the Windlord",
        "Wickerclaw",
        "Shockspitter",
        "Lesser Opal Spellstone",
        "Confessor Paletress",
        "Jolly Roger",
        "Crooked Cook",
        "Secure the Deck",
        "Savage Combatant",
        "Toxic Reinforcements",
        "Shadowbomber",
        "Parched Desperado",
        "Stoneskin Armorer",
        "Burning Heart",
        "Lesser Jasper Spellstone",
        "Felfire Deadeye",
        "Sock Puppet Slitherspear",
        "Rake",
        "Pounce",
        "Bloodseeker",
        "Sand Art Elemental",
        "Multi-Strike",
        "Defias Cannoneer",
        "Dreadprison Glaive",
        "Keeneye Spotter",
        "Feast and Famine",
        "Battlefiend",
        "Going Down Swinging",
        "Spread the Word",
        "Park Panther",
        "Self-Sharpening Sword",
        "Battleworn Vanguard",
        "Captain Galvangar",
        "Khaz'goroth"
      ]) ->
        :"Malfurion Stormrage"

      min_count?(card_info, 26, [
        "Acolyte of Death",
        "Arms Dealer",
        "Army of the Dead",
        "BEEEES!!!",
        "Battlefield Necromancer",
        "Body Bagger",
        "Bonedigger Geist",
        "Corpse Bride",
        "Corpse Farm",
        "Crop Rotation",
        "Eulogizer",
        "Fistful of Corpses",
        "Heart Strike",
        "Hematurge",
        "Lingering Zombie",
        "Malignant Horror",
        "Maw and Paw",
        "Mining Casualties",
        "Mosh Pit",
        "Necrotic Mortician",
        "Plagued Grain",
        "Remote Control",
        "Runes of Darkness",
        "Sickly Grimewalker",
        "Sinister Soulcage",
        "Stitched Giant",
        "The Scourge",
        "Tomb Guardians",
        "Unliving Champion",
        "Ymirjar Deathbringer"
      ]) ->
        :"The Lich King"

      min_count?(card_info, 31, [
        "Murgur Murgurgle",
        "Coldlight Seer",
        "Unite the Murlocs",
        "Sir Finley, Sea Guide",
        "Grimscale Oracle",
        "Gentle Megasaur",
        "Amalgam of the Deep",
        "Painter's Virtue",
        "Clownfish",
        "Hand of A'dal",
        "Voidgill",
        "Adaptation",
        "Aquatic Form",
        "Toxfin",
        "Innervate",
        "Lushwater Murcenary",
        "Primalfin Lookout",
        "Nofin Can Stop Us",
        "Murloc Tidecaller",
        "Mutate",
        "South Coast Chieftain",
        "Rotgill",
        "Underbelly Angler",
        "Rock Bottom",
        "Consecration",
        "Murloc Warleader",
        "Auctionhouse Gavel",
        "Murloc Growfin",
        "Everyfin is Awesome",
        "Hydrologist",
        "Rockpool Hunter",
        "Nofin's Imp-ossible",
        "Spawnpool Forager",
        "Bloodscent Vilefin",
        "Murloc Knight"
      ]) ->
        :"Uther Lightbringer"

      min_count?(card_info, 26, [
        "Archwitch Willow",
        "Bloodreaver Gul'dan",
        "Cannibalize",
        "Caria Felsoul",
        "Chemical Spill",
        "Crane Game",
        "Dark Peddler",
        "Darkbomb",
        "Defile",
        "Demonic Assault",
        "Dirge of Despair",
        "Doomsayer",
        "Endgame",
        "Enhanced Dreadlord",
        "Game Master Nemsy",
        "Kobold Librarian",
        "Loken, Jailer of Yogg-Saron",
        "Miracle Salesman",
        "Mortal Coil",
        "Pit Commander",
        "Prince Taldaram",
        "Raging Felscreamer",
        "Ring Matron",
        "Sigil of Reckoning",
        "Taintheart Tormenter",
        "Touch of the Nathrezim",
        "Voidcaller",
        "Voidlord",
        "Warden of Chains",
        "Wretched Queen"
      ]) ->
        :"Gul'dan"

      min_count?(card_info, 41, [
        "Raptor Hatchling",
        "Bibliomite",
        "Greedy Partner",
        "Momentum",
        "Rehydrate",
        "Prize Plunderer",
        "Sky Mother Aviana",
        "Scabbs Cutterbutter",
        "Bargain Bin Buccaneer",
        "Malevolent Strike",
        "Backstab",
        "Silence",
        "Dehydrate",
        "Wandmaker",
        "Frostwolf Warmaster",
        "Ignite",
        "Dark Peddler",
        "Umbral Owl",
        "Brain Freeze",
        "Floppy Hydra",
        "First Day of School",
        "Playhouse Giant",
        "Dart Throw",
        "Cold Blood",
        "Sherazin, Corpse Flower",
        "Edwin VanCleef",
        "SI:7 Agent",
        "SI:7 Extortion",
        "Biteweed",
        "Stowaway",
        "Photographer Fizzle",
        "Wayward Sage",
        "One Hit Wonder",
        "Foxy Fraud",
        "Conjure Mana Biscuit",
        "Sharp-Eyed Seeker",
        "Preparation",
        "Tour Guide",
        "Dispose of Evidence",
        "Eviscerate",
        "Counterfeit Coin",
        "Spymistress",
        "Bounty Wrangler",
        "Serrated Bone Spike",
        "Coerce"
      ]) ->
        :"Valeera Sanguinar"

      min_count?(card_info, 46, [
        "Apotheosis",
        "Blessing of Authority",
        "Silvermoon Portal",
        "Enter the Coliseum",
        "Banana Buffoon",
        "Boon of the Ascended",
        "Explosive Evolution",
        "Keeper's Strength",
        "Devout Pupil",
        "Eydis Darkbane",
        "Hi Ho Silverwing",
        "Stonehearth Vindicator",
        "Saidan the Scarlet",
        "Partner in Crime",
        "Noble Mount",
        "Molten Reflection",
        "Hand of A'dal",
        "Echoing Ooze",
        "Sethekk Veilweaver",
        "Ramming Mount",
        "Kotori Lightblade",
        "Spikeridged Steed",
        "High Abbess Alura",
        "Twisted Frostwing",
        "Cloakscale Chemist",
        "Hold the Bridge",
        "Blood Matriarch Liadrin",
        "Unidentified Elixir",
        "Camouflage Mount",
        "Seal of Blood",
        "Great Hall",
        "Nerubian Egg",
        "Elekk Mount",
        "Gift of Luminance",
        "Kodo Mount",
        "Blistering Rot",
        "Consecration",
        "Scarab Egg",
        "The Voraxx",
        "Argent Braggart",
        "Lady Liadrin",
        "Sunwing Squawker",
        "Earthen Scales",
        "Power Chord: Synchronize",
        "Blademaster Samuro",
        "Sweeping Strikes",
        "For Quel'Thalas!",
        "Battle Vicar",
        "Clear Conscience",
        "Myrmidon"
      ]) ->
        :"Uther Lightbringer"

      min_count?(card_info, 36, [
        "Ancient Krakenbane",
        "Flame Geyser",
        "Commander Sivara",
        "Snake Eyes",
        "Raj Naz'jan",
        "Dryscale Deputy",
        "Naga Giant",
        "Amalgam of the Deep",
        "Mantle Shaper",
        "Vast Wisdom",
        "Aquatic Form",
        "Arrow Smith",
        "Barbed Nets",
        "Seaweed Strike",
        "Coral Keeper",
        "Lady S'theno",
        "Parched Desperado",
        "Card Grader",
        "Lady Naz'jar",
        "Void Scripture",
        "School Teacher",
        "Gone Fishin'",
        "Predation",
        "Load the Chamber",
        "Murkwater Scribe",
        "Queen Azshara",
        "Queensguard",
        "Ray of Frost",
        "Wayward Sage",
        "Dozing Kelpkeeper",
        "Gifts of Azshara",
        "Naga's Pride",
        "Runed Orb",
        "Oasis Outlaws",
        "Priestess Valishj",
        "Elemental Inspiration",
        "Vicious Slitherspear",
        "Primordial Glyph",
        "Spellcoiler",
        "Handmaiden"
      ]) ->
        :"Jaina Proudmoore"

      min_count?(card_info, 36, [
        "Devouring Plague",
        "Jan'alai, the Dragonhawk",
        "Mortal Eradication",
        "Zilliax",
        "Sigil of Alacrity",
        "The Soularium",
        "Hidden Gem",
        "Drain Soul",
        "Ball Hog",
        "Cannibalize",
        "Careless Crafter",
        "Molten Giant",
        "Burden of Pride",
        "Twilight Torrent",
        "Idol's Adoration",
        "Khartut Defender",
        "Papercraft Angel",
        "Thornveil Tentacle",
        "Void Scripture",
        "Bracing Cold",
        "Imprisoned Horror",
        "Mistress of Mixtures",
        "Sheriff Barrelbrim",
        "Funhouse Mirror",
        "Dar'Khan Drathir",
        "Rotten Applebaum",
        "Soul Rend",
        "Death's Head Cultist",
        "Unstable Shadow Blast",
        "Touch of the Nathrezim",
        "Shadowcloth Needle",
        "Tamsin Roame",
        "Tour Guide",
        "Darkbomb",
        "Fan Club",
        "Shadowblade Slinger",
        "Revenge",
        "Mordresh Fire Eye",
        "Spirit Lash",
        "Astalor Bloodsworn"
      ]) ->
        :"Gul'dan"

      min_count?(card_info, 36, [
        "Dalaran Librarian",
        "Lightspawn",
        "Kologarn",
        "Humongous Razorleaf",
        "Unsleeping Soul",
        "Whispers of the Deep",
        "Package Runner",
        "Boon of the Ascended",
        "Wailing Soul",
        "Gigafin",
        "Ancient Watcher",
        "Eerie Statue",
        "Deafen",
        "Fight Over Me",
        "Selfish Shellfish",
        "Purifying Power",
        "Silence",
        "Origami Frog",
        "Incorporeal Corporal",
        "Smothering Starfish",
        "Attorney-at-Maw",
        "Idol's Adoration",
        "Royal Librarian",
        "Bittertide Hydra",
        "Imposing Anubisath",
        "Frozen Crusher",
        "Azsharan Ritual",
        "Needlerock Totem",
        "Cornelius Roame",
        "Focused Will",
        "Jepetto Joybuzz",
        "Malefic Rook",
        "Silas Darkmoon",
        "Chalk Artist",
        "Neferset Thrasher",
        "Loken, Jailer of Yogg-Saron",
        "Najak Hexxen",
        "Purify",
        "Arcane Watcher",
        "Breakdance"
      ]) ->
        :"Anduin Wrynn"

      min_count?(card_info, 46, [
        "Carving Chisel",
        "Lightning Bloom",
        "Guidance",
        "Amitus, the Peacekeeper",
        "EVIL Totem",
        "Vessina",
        "Thorim, Stormlord",
        "Sludge Slurper",
        "Totemic Might",
        "Amalgam of the Deep",
        "Totally Totems",
        "Totemic Surge",
        "Golganneth, the Thunderer",
        "Likkim",
        "Aggramar, the Avenger",
        "Primal Talismans",
        "Aman'Thul",
        "Ancestral Knowledge",
        "Anchored Totem",
        "Sinstone Totem",
        "Mana Tide Totem",
        "Don't Stand in the Fire!",
        "Life from Death",
        "Party Favor Totem",
        "Totem Golem",
        "Tuskarr Totemic",
        "Thing from Below",
        "Runic Carvings",
        "Primal Fusion",
        "Draenei Totemcarver",
        "Totem Goliath",
        "Altered Chord",
        "Gigantotem",
        "Turn the Tides",
        "Flametongue Totem",
        "Needlerock Totem",
        "Ancient Totem",
        "Totemic Evidence",
        "Deathweaver Aura",
        "Observer of Myths",
        "Splitting Axe",
        "Shock Hopper",
        "Lightning Storm",
        "V-07-TR-0N Prime",
        "Jukebox Totem",
        "Tunnel Trogg",
        "Totemic Reflection",
        "Storm's Wrath",
        "Khaz'goroth",
        "Remixed Totemcarver"
      ]) ->
        :Thrall

      min_count?(card_info, 41, [
        "Party Animal",
        "Quality Assurance",
        "N'Zoth, God of the Deep",
        "Drum Soloist",
        "Razormane Battleguard",
        "Frightened Flunky",
        "Boon of the Ascended",
        "Keeper's Strength",
        "Last Stand",
        "Ramming Speed",
        "Brutal Annihilan",
        "Shining Sentinel",
        "Deafen",
        "Plaguemaw the Rotting",
        "Into the Fray",
        "Glory Chaser",
        "Bronze Dragonknight",
        "Treasure Guard",
        "Brawl",
        "Detonation Juggernaut",
        "Power Slider",
        "Grimestreet Outfitter",
        "Rock Master Voone",
        "Remixed Rhapsody",
        "The One-Amalgam Band",
        "Star Power",
        "Messenger Buzzard",
        "I Know a Guy",
        "Undying Disciple",
        "Conditioning (Rank 1)",
        "Blast Tortoise",
        "Remixed Tuning Fork",
        "Nerubian Swarmguard",
        "Sword Eater",
        "Toyrantus",
        "Alliance Bannerman",
        "Botface",
        "Armagedillo",
        "Circus Amalgam",
        "Smuggler's Run",
        "Scrap Golem",
        "Execute",
        "Encumbered Pack Mule",
        "Muscle-o-Tron",
        "Ra-den"
      ]) ->
        :"Garrosh Hellscream"

      min_count?(card_info, 31, [
        "Dreadlord's Bite",
        "Stargazer Luna",
        "Redeemed Pariah",
        "Pocket Sand",
        "Bartend-O-Bot",
        "Kor'vas Bloodthorn",
        "Wretched Exile",
        "Quick Pick",
        "Crimson Sigil Runner",
        "Spectral Sight",
        "Stick Up",
        "Gan'arg Glaivesmith",
        "Edwin, Defias Kingpin",
        "Kurtrus Ashfallen",
        "Glaivetar",
        "Calamity's Grasp",
        "Illidari Studies",
        "SECURITY!!",
        "Chaos Leech",
        "Eye Beam",
        "Instructor Fireheart",
        "Heat Wave",
        "Vengeful Walloper",
        "Misfire",
        "Need for Greed",
        "Wayward Sage",
        "Tough Crowd",
        "Flint Firearm",
        "Benevolent Banker",
        "Rumble Enthusiast",
        "Razorglaive Sentinel",
        "Silver Serpent",
        "Altruis the Outcast",
        "Glowstone Gyreworm",
        "Felerin, the Forgotten"
      ]) ->
        :"Illidan Stormrage"

      true ->
        nil
    end
  end
end
