import Config

# config :backend, QuantumScheduler,
#  jobs: [
#  ]

import_config "cron_bot.exs"

twitch_redirect = "https://www.d0nkey.top/auth/twitch/callback"

config :backend,
  warmup_cache: true,
  auto_migrate: false,
  goatcounter_analytics: false,
  cloudflare_analytics: true,
  gm_stream_send_tweet: true,
  nitropay_demo: false,
  nostrum_slash_command_target: :global,
  thl_discord_id: 534_455_756_129_435_649,
  twitch_bot_chats: [
    "sgt_tbag",
    "d0nkeyhs",
    "d0nkeytop",
    "branka279",
    "dettomon",
    "norwis_",
    "otters_tv",
    "goofyronak",
    "reqvam",
    "emerald_boa"
  ],
  enable_bot: false

config :ueberauth, Ueberauth,
  providers: [
    bnet: {Ueberauth.Strategy.Bnet, []},
    twitch: {Ueberauth.Strategy.Twitch, [callback_url: twitch_redirect]}
  ]

config :ueberauth, Ueberauth.Strategy.Twitch.OAuth,
  client_id: System.get_env("TWITCH_CLIENT_ID") || "",
  client_secret: System.get_env("TWITCH_CLIENT_SECRET") || "",
  redirect_uri: twitch_redirect

# For production, don't f "d0nkey.top"orget to configure the url host
# to something meaningful, Phoenix uses this information
# when generating URLs.
#
# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix phx.digest` task,
# which you should run after static files are built and
# before starting your production server.
config :backend, BackendWeb.Endpoint,
  url: [scheme: "https", host: "www.d0nkey.top", port: 443],
  http: [protocol_options: [max_request_line_length: 32_768, max_header_value_length: 32_768]],
  check_origin: [
    "//d0nkey.top",
    "//hsguru.com",
    "https://www.d0nkey.top",
    "https://www.hsguru.com"
  ],
  # force_ssl: [rewrite_on: [:x_forwarded_proto]],
  cache_static_manifest: "priv/static/cache_manifest.json"

# Do not print debug messages in production
config :logger, level: :warning

# ## SSL Support
#
# To get SSL working, you will need to add the `https` key
# to the previous section and set your `:url` port to 443:
#
#     config :backend, BackendWeb.Endpoint,
#       ...
#       url: [host: "example.com", port: 443],
#       https: [
#         :inet6,
#         port: 443,
#         cipher_suite: :strong,
#         keyfile: System.get_env("SOME_APP_SSL_KEY_PATH"),
#         certfile: System.get_env("SOME_APP_SSL_CERT_PATH")
#       ]
#
# The `cipher_suite` is set to `:strong` to support only the
# latest and more secure SSL ciphers. This means old browsers
# and clients may not be supported. You can set it to
# `:compatible` for wider support.
#
# `:keyfile` and `:certfile` expect an absolute path to the key
# and cert in disk or a relative path inside priv, for example
# "priv/ssl/server.key". For all supported SSL configuration
# options, see https://hexdocs.pm/plug/Plug.SSL.html#configure/1
#
# We also recommend setting `force_ssl` in your endpoint, ensuring
# no data is ever sent via http, always redirecting to https:
#
#     config :backend, BackendWeb.Endpoint,
#       force_ssl: [hsts: true]
#
# Check `Plug.SSL` for all available options in `force_ssl`.

# Finally import the config/prod.secret.exs which loads secrets
# and configuration from environment variables.
import_config "prod.secret.exs"
